/* global require */
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
for(const key of ["DB_HOST","DB_PORT","DB_NAME","DB_USER","DB_PASSWORD"])process.env[key]||="test";process.env.DB_PORT="5432";
const pool=require("../db"),service=require("../src/orangePhotosService"),ownerId="11111111-1111-4111-8111-111111111111",familyId="22222222-2222-4222-8222-222222222222",photoId="33333333-3333-4333-8333-333333333333",req={user:{id:ownerId,families:[{id:familyId,role:"member"}]},headers:{}};
async function mocked(responses,action){const original=pool.query;let index=0;pool.query=async()=>responses[Math.min(index++,responses.length-1)];try{return await action();}finally{pool.query=original;}}
test("propietario crea enlace y recibe path",async()=>{const current={id:photoId,owner_user_id:ownerId,public_enabled:false},updated={public_enabled:true,public_token:"token-new",public_revoked_at:null};const result=await mocked([{rows:[current]},{rows:[updated]}],()=>service.updatePublicLink(req,photoId,"photo",false));assert.equal(result.payload.public_link.path,"/public/orangephotos/photo/token-new");});
test("segundo POST conserva token",async()=>{const current={id:photoId,owner_user_id:ownerId,public_enabled:true,public_token:"same",public_revoked_at:null};const result=await mocked([{rows:[current]}],()=>service.updatePublicLink(req,photoId,"photo",false));assert.equal(result.payload.public_link.token,"same");});
test("regenerar cambia token",async()=>{const current={id:photoId,owner_user_id:ownerId,public_enabled:true,public_token:"old"},updated={public_enabled:true,public_token:"new",public_revoked_at:null};const result=await mocked([{rows:[current]},{rows:[updated]}],()=>service.updatePublicLink(req,photoId,"photo",true));assert.notEqual(result.payload.public_link.token,"old");});
test("token vacío público devuelve 404 uniforme",async()=>{const result=await service.publicPhotoByToken("   ");assert.equal(result.status,404);assert.equal(result.code,"PUBLIC_NOT_FOUND");});
test("foto inexistente pública devuelve 404 uniforme",async()=>{const result=await mocked([{rows:[]}],()=>service.publicPhotoByToken("missing"));assert.equal(result.status,404);});
test("álbum archivado o token revocado devuelve 404",async()=>{const result=await mocked([{rows:[]}],()=>service.publicAlbumByToken("revoked"));assert.equal(result.status,404);});
test("ZIP rechaza selección vacía",async()=>{const result=await mocked([{rows:[{id:photoId,title:"A",photo_count:0,public_link_active:true}]}],()=>service.publicAlbumDownloadItems("token",[]));assert.equal(result.status,400);});
test("HTTP no accede directamente a PostgreSQL",()=>{const source=fs.readFileSync(path.join(__dirname,"../src/orangePhotosHttp.js"),"utf8");assert.equal(source.includes('require("../db")'),false);});
test("respuesta pública limita campos",()=>{const source=fs.readFileSync(path.join(__dirname,"../src/orangePhotosService.js"),"utf8");for(const field of ["family_id","owner_user_id","object_key","checksum_sha256","exif_json","shared_people"])assert.equal(/PUBLIC_PHOTO_FIELDS=.*$/m.exec(source)?.[0].includes(field),false);});
