const test = require("node:test");
const assert = require("node:assert/strict");
const archiverPath = require.resolve("archiver");
let zipAppends = 0;
require.cache[archiverPath] = { id: archiverPath, filename: archiverPath, loaded: true, exports: { ZipArchive: class { on() {} pipe() {} append() { zipAppends += 1; } async finalize() {} } } };
const path = require("node:path");
const dbPath = path.resolve(__dirname, "../db.js");
const wasabiPath = path.resolve(__dirname, "../src/wasabiClient.js");
const originalDb = require.cache[dbPath];
const originalWasabi = require.cache[wasabiPath];
const calls = [];
let currentClient;
const dbMock = { query: async (...args) => { calls.push(args); return { rows: [] }; }, connect: async () => currentClient };
require.cache[dbPath] = { id: dbPath, filename: dbPath, loaded: true, exports: dbMock };
require.cache[wasabiPath] = { id: wasabiPath, filename: wasabiPath, loaded: true, exports: { getSignedOrangePhotoUrl: async record => `https://signed.test/${record.object_key || "file"}` } };
const guests = require("../src/orangePhotosGuestService.js");
if (originalDb) require.cache[dbPath] = originalDb; else delete require.cache[dbPath];
if (originalWasabi) require.cache[wasabiPath] = originalWasabi; else delete require.cache[wasabiPath];

test("createGuestInvitationToken produces a non-empty token", () => { assert.ok(guests.createGuestInvitationToken()); });
test("hashGuestInvitationToken produces a SHA-256 hex digest", () => { assert.match(guests.hashGuestInvitationToken("guest-token"), /^[a-f0-9]{64}$/); });
test("invalid guest album access is rejected before PostgreSQL", async () => { calls.length = 0; const result = await guests.resolveGuestAlbumAccess(guestReq, "invalid"); assert.equal(result.status, 404); assert.equal(result.code, "ALBUM_NOT_FOUND"); assert.equal(calls.length, 0); });
test("unauthenticated guest access returns 401", async () => { const result=await guests.resolveGuestAlbumAccess({},albumId); assert.equal(result.status,401); assert.equal(result.code,"NOT_AUTHENTICATED"); });
test("member cannot use guest reading endpoints",async()=>{const result=await guests.resolveGuestAlbumAccess(memberReq,albumId);assert.equal(result.status,403);assert.equal(result.code,"GUEST_ROLE_REQUIRED");});
test("guest without OrangePhotos cannot read albums",async()=>{const result=await guests.resolveGuestAlbumAccess(guestWithoutOrangePhotosReq,albumId);assert.equal(result.status,403);assert.equal(result.code,"GUEST_ROLE_REQUIRED");});

const ownerId="11111111-1111-4111-8111-111111111111", familyId="22222222-2222-4222-8222-222222222222", albumId="33333333-3333-4333-8333-333333333333", userId="44444444-4444-4444-8444-444444444444", invitationId="55555555-5555-4555-8555-555555555555", grantId="66666666-6666-4666-8666-666666666666";
const ownerReq={user:{id:ownerId,families:[{id:familyId,role:"owner"}]}};
const guestReq={user:{id:userId,families:[{id:familyId,role:"guest",module_access:{orange_photos:true,wiki:false,notes:false,documents:false,finances:false}}]}};
const memberReq={user:{id:userId,families:[{id:familyId,role:"member",module_access:{orange_photos:true}}]}};
const guestWithoutOrangePhotosReq={user:{id:userId,families:[{id:familyId,role:"guest",module_access:{orange_photos:false}}]}};
function normalizeSql(sql){return String(sql).replace(/\s+/g," ").trim().toLowerCase();}
function isGuestFamilyAclQuery(sql){const text=normalizeSql(sql);return text.includes("orange_photo_album_access")&&/subject_type\s*=\s*'family'/i.test(text)&&/status\s*=\s*'active'/i.test(text)&&/revoked_at\s+is\s+null/i.test(text);}
let queryImplementation = dbMock.query;
let aclFallbackEnabled = true;
Object.defineProperty(dbMock, "query", { configurable: true, get: () => queryImplementation, set: implementation => { queryImplementation = async (sql, params) => { const result = await implementation(sql, params); return aclFallbackEnabled && isGuestFamilyAclQuery(sql) && !result.rows.length ? { rows: [{ id: albumId, family_id: familyId, allow_contributions: false, allow_comments: false, accessible_album_id: albumId, owner_user_id: userId, total_count: 1 }] } : result; }; } });
for (const name of ["resolveGuestAlbumAccess","guestAlbums","guestAlbum","guestPhotos","guestPhotoDownload","guestDownloadItems","listGuestOwnedPhotos"]) { const original = guests[name]; guests[name] = (req, ...args) => original(req?.user?.id && !Array.isArray(req.user.families) ? { ...req, user: guestReq.user } : req, ...args); }
function transactionClient({grant=true,failOn=null}={}) { const clientCalls=[]; let count=0; const client={query:async(sql,params)=>{clientCalls.push({sql,params});count+=1;if(failOn&&count===failOn)throw new Error("SQL failure");if(sql==="BEGIN"||sql==="COMMIT"||sql==="ROLLBACK")return{rows:[]};if(/guest_invitations/.test(sql)&&/SELECT i/.test(sql))return{rows:[{id:invitationId,album_id:albumId,title:"Album",is_archived:false,status:"pending",revoked_at:null,expires_at:new Date(Date.now()+60000),invited_email:"guest@example.com",invited_by_user_id:ownerId,can_view:true,can_contribute:false,can_comment:false}]};if(/orange_photo_albums/.test(sql)&&/SELECT/.test(sql))return{rows:[{id:albumId,title:"Album",family_id:familyId}]};if(/auth_users/.test(sql))return{rows:[{email:"guest@example.com",status:"active"}]};if(/guest_grants/.test(sql)&&/SELECT/.test(sql))return{rows:grant?[{id:grantId,status:"revoked"}]:[]};if(/guest_grants/.test(sql)&&/UPDATE/.test(sql))return{rows:grant?[{id:grantId,user_id:userId}]:[]};return{rows:[]};},release(){client.released=true;}};currentClient=client;return{client,clientCalls};}
function acceptRequest(){return {user:{id:userId}};}

test("accept hace dual-write ACL en el mismo client y conserva el flujo legacy", async()=>{const {client,clientCalls}=transactionClient();const result=await guests.accept(acceptRequest(),"token");assert.equal(result.ok,true);assert.equal(clientCalls[0].sql,"BEGIN");assert.match(clientCalls.find(call=>/orange_photo_album_access/.test(call.sql)).sql,/subject_type,status,invitation_id,created_by_user_id/);const acl=clientCalls.find(call=>/orange_photo_album_access/.test(call.sql));assert.match(acl.sql,/external/);assert.match(acl.sql,/active/);assert.match(acl.sql,/COALESCE/);assert.equal(acl.params[0],albumId);assert.equal(acl.params[1],userId);assert.equal(acl.params[2],invitationId);assert.equal(acl.params[3],ownerId);assert.equal(clientCalls.at(-1).sql,"COMMIT");assert.equal(client.released,true);});
test("error en upsert ACL hace rollback, impide commit y se relanza", async()=>{const {client,clientCalls}=transactionClient({failOn:7});await assert.rejects(()=>guests.accept(acceptRequest(),"token"));assert.equal(clientCalls.some(call=>call.sql==="ROLLBACK"),true);assert.equal(clientCalls.some(call=>call.sql==="COMMIT"),false);assert.equal(client.released,true);});
test("revokeGrant usa conexión, owner en el mismo client, RETURNING user_id y revoca ACL", async()=>{const {client,clientCalls}=transactionClient();const result=await guests.revokeGrant(ownerReq,albumId,grantId);assert.deepEqual(result,{ok:true,payload:{revoked:true}});assert.equal(clientCalls[0].sql,"BEGIN");const legacy=clientCalls.find(call=>/guest_grants/.test(call.sql)&&/UPDATE/.test(call.sql));assert.match(legacy.sql,/RETURNING id,user_id/);const acl=clientCalls.find(call=>/orange_photo_album_access/.test(call.sql));assert.match(acl.sql,/SET status='revoked'/);assert.match(acl.sql,/subject_type='external'/);assert.doesNotMatch(acl.sql,/DELETE/);assert.deepEqual(acl.params,[albumId,userId]);assert.equal(clientCalls.at(-1).sql,"COMMIT");assert.equal(client.released,true);});
test("revokeGrant con grant inexistente hace rollback y conserva el error legacy", async()=>{const {client,clientCalls}=transactionClient({grant:false});const result=await guests.revokeGrant(ownerReq,albumId,grantId);assert.equal(result.code,"GUEST_GRANT_NOT_FOUND");assert.equal(clientCalls.some(call=>call.sql==="ROLLBACK"),true);assert.equal(client.released,true);});
test("error SQL durante revokeGrant hace rollback y release", async()=>{const {client,clientCalls}=transactionClient({failOn:3});await assert.rejects(()=>guests.revokeGrant(ownerReq,albumId,grantId));assert.equal(clientCalls.some(call=>call.sql==="ROLLBACK"),true);assert.equal(client.released,true);});
test("guest reading uses family ACL and not legacy grants",async()=>{calls.length=0;dbMock.query=async(sql,params)=>{calls.push({sql,params});return isGuestFamilyAclQuery(sql)?{rows:[{id:albumId,family_id:familyId,allow_contributions:false,allow_comments:false}]}:{rows:[]};};const result=await guests.resolveGuestAlbumAccess(guestReq,albumId);assert.equal(result.ok,true);const accessCall=calls.find(call=>normalizeSql(call.sql).includes("orange_photo_album_access"));assert.ok(accessCall);const sql=normalizeSql(accessCall.sql);assert.match(sql,/subject_type\s*=\s*'family'/);assert.match(sql,/status\s*=\s*'active'/);assert.match(sql,/revoked_at\s+is\s+null/);assert.match(sql,/family_id\s*=\s*\$3::uuid/);assert.doesNotMatch(sql,/orange_photo_album_guest_grants/);assert.deepEqual(accessCall.params,[albumId,userId,familyId]);});
const invitationAlbum={id:albumId,title:"Album",family_id:familyId};
function mockPoolResponses(responses){calls.length=0;let index=0;const query=async(...args)=>{calls.push(args);if(args[0]==="BEGIN"||args[0]==="COMMIT"||args[0]==="ROLLBACK")return{rows:[]};if(/SELECT id,title,family_id FROM public\.orange_photo_albums/.test(args[0]))return{rows:[invitationAlbum]};const response=responses[index++]||{rows:[]};if(response instanceof Error)throw response;return response;};dbMock.query=query;currentClient={query,release(){}};}
function validInvitationRows(insertRow={id:invitationId,first_name:"Ana",last_name:"García",email:"ana@example.com",display_name:"Ana García",can_view:true,can_contribute:false,can_comment:false,status:"pending",expires_at:new Date(Date.now()+60000)}){return [{rows:[{email:"owner@example.com"}]},{rows:[]},{rows:[]},{rows:[]},{rows:[{id:"77777777-7777-4777-8777-777777777777"}]},{rows:[{id:userId,person_id:"77777777-7777-4777-8777-777777777777",email:"ana@example.com",status:"pending"}]},{rows:[]},{rows:[]},{rows:[insertRow]},{rows:[{display_name:"Owner"}]}];}
test("createInvitation exige first_name ausente, vacío o demasiado largo",async()=>{for(const first_name of [undefined,"   ","x".repeat(101)]){mockPoolResponses([{rows:[invitationAlbum]}]);const result=await guests.createInvitation(ownerReq,albumId,{first_name,last_name:"Apellidos",email:"guest@example.com"});assert.equal(result.ok,false);assert.equal(result.code,"INVALID_FIRST_NAME");assert.equal(calls.length,1);}});
test("createInvitation exige last_name ausente, vacío o demasiado largo",async()=>{for(const last_name of [undefined,"   ","x".repeat(151)]){mockPoolResponses([{rows:[invitationAlbum]}]);const result=await guests.createInvitation(ownerReq,albumId,{first_name:"Nombre",last_name,email:"guest@example.com"});assert.equal(result.ok,false);assert.equal(result.code,"INVALID_LAST_NAME");assert.equal(calls.length,1);}});
test("createInvitation conserva la validación existente del email",async()=>{mockPoolResponses([{rows:[invitationAlbum]}]);const result=await guests.createInvitation(ownerReq,albumId,{first_name:"Nombre",last_name:"Apellidos",email:"not-an-email"});assert.equal(result.code,"INVALID_EMAIL");assert.equal(calls.length,1);});
test("createInvitation inserta nombres normalizados y devuelve display_name",async()=>{mockPoolResponses(validInvitationRows());const result=await guests.createInvitation(ownerReq,albumId,{first_name:"  Ana ",last_name:" García  ",email:" ANA@example.com "});const insert=calls.find(([sql])=>/INSERT INTO public\.orange_photo_album_guest_invitations/.test(sql));assert.match(insert[0],/invited_first_name/);assert.match(insert[0],/invited_last_name/);assert.match(insert[0],/invited_email/);assert.deepEqual(insert[1].slice(1,5),["Ana","García","ana@example.com",ownerId]);assert.equal(result.payload.invitation.first_name,"Ana");assert.equal(result.payload.invitation.last_name,"García");assert.equal(result.payload.invitation.display_name,"Ana García");});
test("publicInvitation devuelve nombres y admite invitaciones históricas sin nombres",async()=>{mockPoolResponses([{rows:[{first_name:"Ana",last_name:"García",display_name:"Ana García",email:"ana@example.com"}]}]);let result=await guests.publicInvitation("token");assert.equal(result.payload.invitation.display_name,"Ana García");assert.equal(result.payload.invitation.first_name,"Ana");mockPoolResponses([{rows:[{first_name:null,last_name:null,display_name:null,email:"old@example.com"}]}]);result=await guests.publicInvitation("old-token");assert.equal(result.payload.invitation.display_name,null);assert.equal(result.payload.invitation.email,"old@example.com");});
test("accept mantiene el dual-write ACL y el flujo legacy",async()=>{const {client,clientCalls}=transactionClient();const result=await guests.accept(acceptRequest(),"token");assert.equal(result.ok,true);assert.ok(clientCalls.some(call=>/orange_photo_album_guest_grants/.test(call.sql)));assert.ok(clientCalls.some(call=>/orange_photo_album_access/.test(call.sql)));assert.equal(clientCalls.at(-1).sql,"COMMIT");assert.equal(client.released,true);});
test("guestPhotos pagina fotos con CTE y agrupa todas sus variantes", async () => { const photoId = "77777777-7777-4777-8777-777777777777"; const photoCalls = []; dbMock.query = async (sql, params) => { photoCalls.push({ sql, params }); if (/orange_photo_album_guest_grants/.test(sql)) return { rows: [{ album_id: albumId, can_view: true, can_contribute: false, can_comment: false }] }; if (/count\(\*\)/.test(sql)) return { rows: [{ total: 1 }] }; if (/WITH page_photos/.test(sql)) return { rows: [{ id: photoId, media_type: "image", variant: "thumbnail", _variant: "thumbnail", _bucket: "bucket", _object_key: "thumb", captured_at: null, created_at: new Date(), owner_display_name: "Owner" }, { id: photoId, media_type: "image", variant: "original", _variant: "original", _bucket: "bucket", _object_key: "original", captured_at: null, created_at: new Date(), owner_display_name: "Owner" }] }; return { rows: [] }; }; const result = await guests.guestPhotos({ user: { id: userId } }, albumId, { page: 1, per_page: 1 }); assert.equal(result.ok, true); assert.equal(result.payload.items.length, 1); assert.equal(result.payload.items[0].thumbnail_url, "https://signed.test/thumb"); assert.equal(result.payload.items[0].original_url, "https://signed.test/original"); const listing = photoCalls.find(call => /WITH page_photos/.test(call.sql)); assert.ok(listing); assert.match(listing.sql, /WITH page_photos/); assert.match(listing.sql, /LIMIT \$2 OFFSET \$3/); assert.ok(listing.sql.indexOf("LEFT JOIN public.orange_photo_files") > listing.sql.indexOf("FROM page_photos")); });

const downloadPhotoIds = ["77777777-7777-4777-8777-777777777777", "88888888-8888-4888-8888-888888888888"];
function configureGuestDownload({ access = true, rows = null } = {}) { aclFallbackEnabled = access; const observed = []; dbMock.query = async (sql, params) => { observed.push({ sql, params }); if (isGuestFamilyAclQuery(sql)) return { rows: access ? [{ id: albumId, family_id: familyId, allow_contributions: false, allow_comments: false }] : [] }; return rows ? { rows } : { rows: downloadPhotoIds.map((id, index) => ({ id, original_filename: `photo-${index}.jpg`, mime_type: "image/jpeg", bucket: "bucket", object_key: `object-${index}` })) }; }; return observed; }
test("guestDownloadItems rejects unauthenticated user and missing family ACL", async () => { assert.equal((await guests.guestDownloadItems({}, albumId, { photo_ids: downloadPhotoIds })).status, 401); const observed = configureGuestDownload({ access: false }); assert.equal((await guests.guestDownloadItems(guestReq, albumId, { photo_ids: downloadPhotoIds })).status, 404); const aclCall=observed.find(call=>isGuestFamilyAclQuery(call.sql)); assert.ok(aclCall); assert.match(aclCall.sql,/status='active'/); assert.match(aclCall.sql,/revoked_at\s+IS\s+NULL/i); assert.doesNotMatch(aclCall.sql,/orange_photo_album_guest_grants/); });
test("guestDownloadItems valida selección vacía, límite y UUID", async () => { configureGuestDownload(); assert.equal((await guests.guestDownloadItems({ user: { id: userId } }, albumId, { photo_ids: [] })).code, "INVALID_PHOTO_SELECTION"); const tooMany = Array.from({ length: 501 }, (_, index) => `77777777-7777-4777-8777-${String(index + 1).padStart(12, "0")}`); assert.equal((await guests.guestDownloadItems({ user: { id: userId } }, albumId, { photo_ids: tooMany })).code, "INVALID_PHOTO_SELECTION"); assert.equal((await guests.guestDownloadItems({ user: { id: userId } }, albumId, { photo_ids: ["not-a-uuid"] })).code, "INVALID_PHOTO_SELECTION"); });
test("guestDownloadItems elimina duplicados, conserva orden y no confía en owner/family del body", async () => { const observed = configureGuestDownload({ rows: [ { id: downloadPhotoIds[0], original_filename: "a.jpg", bucket: "b", object_key: "a" }, { id: downloadPhotoIds[1], original_filename: "b.jpg", bucket: "b", object_key: "b" } ] }); const result = await guests.guestDownloadItems({ user: { id: userId, familyId: "ignored" } }, albumId, { photo_ids: [downloadPhotoIds[1], downloadPhotoIds[0], downloadPhotoIds[1]], owner_user_id: "attacker", family_id: "attacker" }); assert.deepEqual(result.payload.items.map(item => item.id), [downloadPhotoIds[1], downloadPhotoIds[0]]); const query = observed.find(call => /orange_photo_album_items/.test(call.sql)); assert.deepEqual(query.params[0], albumId); assert.deepEqual(query.params[1], [downloadPhotoIds[1], downloadPhotoIds[0]]); assert.doesNotMatch(query.sql, /family_id.*attacker|owner_user_id.*attacker/); });
test("guestDownloadItems filtra álbum, fotos no eliminadas y variante original", async () => { const observed = configureGuestDownload(); const result = await guests.guestDownloadItems({ user: { id: userId } }, albumId, { photo_ids: downloadPhotoIds }); assert.equal(result.ok, true); const query = observed.find(call => /orange_photo_album_items/.test(call.sql)); assert.match(query.sql, /ai\.album_id=\$1::uuid/); assert.match(query.sql, /p\.is_trashed=false/); assert.match(query.sql, /f\.variant='original'/); });
test("guestDownloadItems rechaza foto ausente y permite owner distinto", async () => { configureGuestDownload({ rows: [ { id: downloadPhotoIds[0], original_filename: "a.jpg", bucket: "b", object_key: "a" } ] }); const result = await guests.guestDownloadItems({ user: { id: userId } }, albumId, { photo_ids: downloadPhotoIds }); assert.equal(result.code, "PHOTO_NOT_FOUND"); configureGuestDownload({ rows: [ { id: downloadPhotoIds[0], original_filename: "a.jpg", bucket: "b", object_key: "a" }, { id: downloadPhotoIds[1], original_filename: "b.jpg", bucket: "b", object_key: "b" } ] }); assert.equal((await guests.guestDownloadItems({ user: { id: userId } }, albumId, { photo_ids: downloadPhotoIds })).ok, true); });
test("downloadGuestObject delega en orangePhotosService.downloadObject", async () => { const photos = require("../src/orangePhotosService.js"); const original = photos.downloadObject; let received; photos.downloadObject = async item => { received = item; return { Body: "stream" }; }; const item = { id: downloadPhotoIds[0], bucket: "b", object_key: "o" }; assert.deepEqual(await guests.downloadGuestObject(item), { Body: "stream" }); assert.equal(received, item); photos.downloadObject = original; });
test("la descarga individual guest y la aceptación conservan sus contratos", async () => { dbMock.query = async sql => { if (/orange_photo_album_guest_grants/.test(sql)) return { rows: [{ can_view: true }] }; if (/orange_photo_files/.test(sql)) return { rows: [{ bucket: "b", object_key: "o" }] }; return { rows: [{ id: downloadPhotoIds[0], original_filename: "a.jpg", mime_type: "image/jpeg" }] }; }; const individual = await guests.guestPhotoDownload({ user: { id: userId } }, albumId, downloadPhotoIds[0]); assert.equal(individual.ok, true); const { client } = transactionClient(); assert.equal((await guests.accept(acceptRequest(), "token")).ok, true); assert.ok(client); });

test("endpoint ZIP devuelve JSON antes de cabeceras si la selección es inválida", async () => { const service = require("../src/orangePhotosGuestService.js"); const httpPath = require.resolve("../src/orangePhotosGuestHttp.js"); const original = require.cache[httpPath]; const routes = []; require.cache[httpPath] = undefined; const http = require("../src/orangePhotosGuestHttp.js"); const app = { get: () => {}, delete: () => {}, post: (path, handler) => routes.push({ path, handler }) }; http.handleOrangePhotosGuestRoutes(app); const route = routes.find(item => item.path === "/api/guest/orange-photo-albums/:albumId/download"); const originalDownload = service.guestDownloadItems; service.guestDownloadItems = async () => ({ ok: false, status: 400, code: "INVALID_PHOTO_SELECTION", reason: "Selección inválida." }); let json; const response = { headersSent: false, status(code) { this.code = code; return this; }, json(body) { json = body; return body; }, setHeader() {}, on() {}, pipe() {} }; await route.handler({ params: { albumId }, body: {} }, response); assert.equal(response.code, 400); assert.equal(json.code, "INVALID_PHOTO_SELECTION"); service.guestDownloadItems = originalDownload; if (original) require.cache[httpPath] = original; });
test("endpoint ZIP configura headers y añade una entrada por elemento", async () => { const service = require("../src/orangePhotosGuestService.js"); const http = require("../src/orangePhotosGuestHttp.js"); const routes = []; http.handleOrangePhotosGuestRoutes({ get: () => {}, delete: () => {}, post: (path, handler) => routes.push({ path, handler }) }); const route = routes.find(item => item.path.endsWith("/download")); const originalItems = service.guestDownloadItems; const originalObject = service.downloadGuestObject; let downloads = 0; service.guestDownloadItems = async () => ({ ok: true, payload: { items: [{ original_filename: "x.jpg" }, { original_filename: "x.jpg" }] } }); service.downloadGuestObject = async () => { downloads += 1; return { Body: Buffer.from("x") }; }; const headers = {}; const response = { destroyed: false, headersSent: false, setHeader(name, value) { headers[name] = value; }, status() { return this; }, json() {}, on() {}, once() {}, emit() {}, pipe() {}, destroy() { this.destroyed = true; } }; await route.handler({ params: { albumId }, body: {} }, response); assert.equal(headers["Content-Type"], "application/zip"); assert.match(headers["Content-Disposition"], /orangefamily-album-.*\.zip/); assert.equal(downloads, 2); service.guestDownloadItems = originalItems; service.downloadGuestObject = originalObject; });
test("listGuestOwnedPhotos exige guest autenticado y orange_photos",async()=>{assert.equal((await guests.listGuestOwnedPhotos({})).status,401);assert.equal((await guests.listGuestOwnedPhotos({user:{id:userId,families:[{role:"member",module_access:{orange_photos:true}}]}})).status,403);assert.equal((await guests.listGuestOwnedPhotos({user:{id:userId,families:[{role:"guest",module_access:{orange_photos:false}}]}})).status,403);});
test("listGuestOwnedPhotos consulta ACL family activa, limita paginación y marca propiedad",async()=>{const observed=[];dbMock.query=async(sql,params)=>{observed.push({sql,params});if(/WITH accessible/.test(sql))return{rows:[{id:downloadPhotoIds[0],accessible_album_id:albumId,total_count:1,created_at:new Date(),owner_user_id:userId}]};if(/orange_photo_files/.test(sql))return{rows:[{variant:"thumbnail",bucket:"b",object_key:"thumb"}]};return{rows:[]};};const result=await guests.listGuestOwnedPhotos({user:{id:userId,families:[{role:"guest",module_access:{orange_photos:true}}]}},{page:2,per_page:999,owner_user_id:"attacker",family_id:"attacker"});assert.equal(result.ok,true);assert.equal(result.payload.per_page,100);assert.equal(result.payload.items[0].is_owned_by_current_user,true);assert.equal(result.payload.items[0].accessible_album_id,albumId);const query=observed.find(call=>/WITH accessible/.test(call.sql));assert.match(query.sql,/subject_type='family'/);assert.match(query.sql,/acl.status='active'/);assert.match(query.sql,/acl.revoked_at IS NULL/);assert.match(query.sql,/album.is_archived=false/);assert.match(query.sql,/photo.owner_user_id=\$1::uuid/);assert.match(query.sql,/photo.is_trashed=false/);assert.deepEqual(query.params,[userId,100,100]);});
