const test = require("node:test");
const assert = require("node:assert/strict");
const path = require("node:path");
const dbPath = path.resolve(__dirname, "../db.js");
const wasabiPath = path.resolve(__dirname, "../src/wasabiClient.js");
const originalDb = require.cache[dbPath];
const originalWasabi = require.cache[wasabiPath];
const calls = [];
let currentClient;
const dbMock = { query: async (...args) => { calls.push(args); return { rows: [] }; }, connect: async () => currentClient };
require.cache[dbPath] = { id: dbPath, filename: dbPath, loaded: true, exports: dbMock };
require.cache[wasabiPath] = { id: wasabiPath, filename: wasabiPath, loaded: true, exports: { getSignedOrangePhotoUrl: async record => `https://signed.test/${record.object_key || "file"}` } };
const guests = require("../src/orangePhotosGuestService.js");
if (originalDb) require.cache[dbPath] = originalDb; else delete require.cache[dbPath];
if (originalWasabi) require.cache[wasabiPath] = originalWasabi; else delete require.cache[wasabiPath];

test("createGuestInvitationToken produces a non-empty token", () => { assert.ok(guests.createGuestInvitationToken()); });
test("hashGuestInvitationToken produces a SHA-256 hex digest", () => { assert.match(guests.hashGuestInvitationToken("guest-token"), /^[a-f0-9]{64}$/); });
test("invalid guest album access is rejected before PostgreSQL", async () => { calls.length = 0; const result = await guests.resolveGuestAlbumAccess({ user: { id: "user" } }, "invalid"); assert.equal(result.status, 404); assert.equal(calls.length, 0); });
test("unauthenticated guest access returns 401", async () => { assert.equal((await guests.resolveGuestAlbumAccess({}, "invalid")).status, 401); });

const ownerId="11111111-1111-4111-8111-111111111111", familyId="22222222-2222-4222-8222-222222222222", albumId="33333333-3333-4333-8333-333333333333", userId="44444444-4444-4444-8444-444444444444", invitationId="55555555-5555-4555-8555-555555555555", grantId="66666666-6666-4666-8666-666666666666";
const ownerReq={user:{id:ownerId,families:[{id:familyId,role:"owner"}]}};
function transactionClient({grant=true,failOn=null}={}) { const clientCalls=[]; let count=0; const client={query:async(sql,params)=>{clientCalls.push({sql,params});count+=1;if(failOn&&count===failOn)throw new Error("SQL failure");if(sql==="BEGIN"||sql==="COMMIT"||sql==="ROLLBACK")return{rows:[]};if(/guest_invitations/.test(sql)&&/SELECT i/.test(sql))return{rows:[{id:invitationId,album_id:albumId,title:"Album",is_archived:false,status:"pending",revoked_at:null,expires_at:new Date(Date.now()+60000),invited_email:"guest@example.com",invited_by_user_id:ownerId,can_view:true,can_contribute:false,can_comment:false}]};if(/orange_photo_albums/.test(sql)&&/SELECT/.test(sql))return{rows:[{id:albumId,title:"Album",family_id:familyId}]};if(/auth_users/.test(sql))return{rows:[{email:"guest@example.com",status:"active"}]};if(/guest_grants/.test(sql)&&/SELECT/.test(sql))return{rows:grant?[{id:grantId,status:"revoked"}]:[]};if(/guest_grants/.test(sql)&&/UPDATE/.test(sql))return{rows:grant?[{id:grantId,user_id:userId}]:[]};return{rows:[]};},release(){client.released=true;}};currentClient=client;return{client,clientCalls};}
function acceptRequest(){return {user:{id:userId}};}

test("accept hace dual-write ACL en el mismo client y conserva el flujo legacy", async()=>{const {client,clientCalls}=transactionClient();const result=await guests.accept(acceptRequest(),"token");assert.equal(result.ok,true);assert.equal(clientCalls[0].sql,"BEGIN");assert.match(clientCalls.find(call=>/orange_photo_album_access/.test(call.sql)).sql,/subject_type,status,invitation_id,created_by_user_id/);const acl=clientCalls.find(call=>/orange_photo_album_access/.test(call.sql));assert.match(acl.sql,/external/);assert.match(acl.sql,/active/);assert.match(acl.sql,/COALESCE/);assert.equal(acl.params[0],albumId);assert.equal(acl.params[1],userId);assert.equal(acl.params[2],invitationId);assert.equal(acl.params[3],ownerId);assert.equal(clientCalls.at(-1).sql,"COMMIT");assert.equal(client.released,true);});
test("error en upsert ACL hace rollback, impide commit y se relanza", async()=>{const {client,clientCalls}=transactionClient({failOn:7});await assert.rejects(()=>guests.accept(acceptRequest(),"token"));assert.equal(clientCalls.some(call=>call.sql==="ROLLBACK"),true);assert.equal(clientCalls.some(call=>call.sql==="COMMIT"),false);assert.equal(client.released,true);});
test("revokeGrant usa conexión, owner en el mismo client, RETURNING user_id y revoca ACL", async()=>{const {client,clientCalls}=transactionClient();const result=await guests.revokeGrant(ownerReq,albumId,grantId);assert.deepEqual(result,{ok:true,payload:{revoked:true}});assert.equal(clientCalls[0].sql,"BEGIN");const legacy=clientCalls.find(call=>/guest_grants/.test(call.sql)&&/UPDATE/.test(call.sql));assert.match(legacy.sql,/RETURNING id,user_id/);const acl=clientCalls.find(call=>/orange_photo_album_access/.test(call.sql));assert.match(acl.sql,/SET status='revoked'/);assert.match(acl.sql,/subject_type='external'/);assert.doesNotMatch(acl.sql,/DELETE/);assert.deepEqual(acl.params,[albumId,userId]);assert.equal(clientCalls.at(-1).sql,"COMMIT");assert.equal(client.released,true);});
test("revokeGrant con grant inexistente hace rollback y conserva el error legacy", async()=>{const {client,clientCalls}=transactionClient({grant:false});const result=await guests.revokeGrant(ownerReq,albumId,grantId);assert.equal(result.code,"GUEST_GRANT_NOT_FOUND");assert.equal(clientCalls.some(call=>call.sql==="ROLLBACK"),true);assert.equal(client.released,true);});
test("error SQL durante revokeGrant hace rollback y release", async()=>{const {client,clientCalls}=transactionClient({failOn:3});await assert.rejects(()=>guests.revokeGrant(ownerReq,albumId,grantId));assert.equal(clientCalls.some(call=>call.sql==="ROLLBACK"),true);assert.equal(client.released,true);});
test("las lecturas guest siguen usando grants legacy y no ACL", async()=>{calls.length=0;await guests.resolveGuestAlbumAccess({user:{id:userId}},albumId);assert.match(calls[0][0],/orange_photo_album_guest_grants/);assert.doesNotMatch(calls[0][0],/orange_photo_album_access/);});
const invitationAlbum={id:albumId,title:"Album",family_id:familyId};
function mockPoolResponses(responses){calls.length=0;let index=0;const query=async(...args)=>{calls.push(args);if(args[0]==="BEGIN"||args[0]==="COMMIT"||args[0]==="ROLLBACK")return{rows:[]};if(/SELECT id,title,family_id FROM public\.orange_photo_albums/.test(args[0]))return{rows:[invitationAlbum]};const response=responses[index++]||{rows:[]};if(response instanceof Error)throw response;return response;};dbMock.query=query;currentClient={query,release(){}};}
function validInvitationRows(insertRow={id:invitationId,first_name:"Ana",last_name:"García",email:"ana@example.com",display_name:"Ana García",can_view:true,can_contribute:false,can_comment:false,status:"pending",expires_at:new Date(Date.now()+60000)}){return [{rows:[{email:"owner@example.com"}]},{rows:[]},{rows:[]},{rows:[]},{rows:[{id:"77777777-7777-4777-8777-777777777777"}]},{rows:[{id:userId,person_id:"77777777-7777-4777-8777-777777777777",email:"ana@example.com",status:"pending"}]},{rows:[]},{rows:[]},{rows:[insertRow]},{rows:[{display_name:"Owner"}]}];}
test("createInvitation exige first_name ausente, vacío o demasiado largo",async()=>{for(const first_name of [undefined,"   ","x".repeat(101)]){mockPoolResponses([{rows:[invitationAlbum]}]);const result=await guests.createInvitation(ownerReq,albumId,{first_name,last_name:"Apellidos",email:"guest@example.com"});assert.equal(result.ok,false);assert.equal(result.code,"INVALID_FIRST_NAME");assert.equal(calls.length,1);}});
test("createInvitation exige last_name ausente, vacío o demasiado largo",async()=>{for(const last_name of [undefined,"   ","x".repeat(151)]){mockPoolResponses([{rows:[invitationAlbum]}]);const result=await guests.createInvitation(ownerReq,albumId,{first_name:"Nombre",last_name,email:"guest@example.com"});assert.equal(result.ok,false);assert.equal(result.code,"INVALID_LAST_NAME");assert.equal(calls.length,1);}});
test("createInvitation conserva la validación existente del email",async()=>{mockPoolResponses([{rows:[invitationAlbum]}]);const result=await guests.createInvitation(ownerReq,albumId,{first_name:"Nombre",last_name:"Apellidos",email:"not-an-email"});assert.equal(result.code,"INVALID_EMAIL");assert.equal(calls.length,1);});
test("createInvitation inserta nombres normalizados y devuelve display_name",async()=>{mockPoolResponses(validInvitationRows());const result=await guests.createInvitation(ownerReq,albumId,{first_name:"  Ana ",last_name:" García  ",email:" ANA@example.com "});const insert=calls.find(([sql])=>/INSERT INTO public\.orange_photo_album_guest_invitations/.test(sql));assert.match(insert[0],/invited_first_name/);assert.match(insert[0],/invited_last_name/);assert.match(insert[0],/invited_email/);assert.deepEqual(insert[1].slice(1,5),["Ana","García","ana@example.com",ownerId]);assert.equal(result.payload.invitation.first_name,"Ana");assert.equal(result.payload.invitation.last_name,"García");assert.equal(result.payload.invitation.display_name,"Ana García");});
test("publicInvitation devuelve nombres y admite invitaciones históricas sin nombres",async()=>{mockPoolResponses([{rows:[{first_name:"Ana",last_name:"García",display_name:"Ana García",email:"ana@example.com"}]}]);let result=await guests.publicInvitation("token");assert.equal(result.payload.invitation.display_name,"Ana García");assert.equal(result.payload.invitation.first_name,"Ana");mockPoolResponses([{rows:[{first_name:null,last_name:null,display_name:null,email:"old@example.com"}]}]);result=await guests.publicInvitation("old-token");assert.equal(result.payload.invitation.display_name,null);assert.equal(result.payload.invitation.email,"old@example.com");});
test("accept mantiene el dual-write ACL y el flujo legacy",async()=>{const {client,clientCalls}=transactionClient();const result=await guests.accept(acceptRequest(),"token");assert.equal(result.ok,true);assert.ok(clientCalls.some(call=>/orange_photo_album_guest_grants/.test(call.sql)));assert.ok(clientCalls.some(call=>/orange_photo_album_access/.test(call.sql)));assert.equal(clientCalls.at(-1).sql,"COMMIT");assert.equal(client.released,true);});
test("guestPhotos pagina fotos con CTE y agrupa todas sus variantes", async () => { const photoId = "77777777-7777-4777-8777-777777777777"; const photoCalls = []; dbMock.query = async (sql, params) => { photoCalls.push({ sql, params }); if (/orange_photo_album_guest_grants/.test(sql)) return { rows: [{ album_id: albumId, can_view: true, can_contribute: false, can_comment: false }] }; if (/count\(\*\)/.test(sql)) return { rows: [{ total: 1 }] }; if (/WITH page_photos/.test(sql)) return { rows: [{ id: photoId, media_type: "image", variant: "thumbnail", _variant: "thumbnail", _bucket: "bucket", _object_key: "thumb", captured_at: null, created_at: new Date(), owner_display_name: "Owner" }, { id: photoId, media_type: "image", variant: "original", _variant: "original", _bucket: "bucket", _object_key: "original", captured_at: null, created_at: new Date(), owner_display_name: "Owner" }] }; return { rows: [] }; }; const result = await guests.guestPhotos({ user: { id: userId } }, albumId, { page: 1, per_page: 1 }); assert.equal(result.ok, true); assert.equal(result.payload.items.length, 1); assert.equal(result.payload.items[0].thumbnail_url, "https://signed.test/thumb"); assert.equal(result.payload.items[0].original_url, "https://signed.test/original"); const listing = photoCalls.find(call => /WITH page_photos/.test(call.sql)); assert.ok(listing); assert.match(listing.sql, /WITH page_photos/); assert.match(listing.sql, /LIMIT \$2 OFFSET \$3/); assert.ok(listing.sql.indexOf("LEFT JOIN public.orange_photo_files") > listing.sql.indexOf("FROM page_photos")); });
