/* global require */
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
for(const key of ["DB_HOST","DB_PORT","DB_NAME","DB_USER","DB_PASSWORD"])process.env[key]||="test";process.env.DB_PORT="5432";
const pool=require("../db"),service=require("../src/orangePhotosService"),ownerId="11111111-1111-4111-8111-111111111111",familyId="22222222-2222-4222-8222-222222222222",photoId="33333333-3333-4333-8333-333333333333",albumId="44444444-4444-4444-8444-444444444444",req={user:{id:ownerId,families:[{id:familyId,role:"member"}]},headers:{}};
async function mocked(responses,action){const original=pool.query;let index=0;pool.query=async()=>responses[Math.min(index++,responses.length-1)];try{return await action();}finally{pool.query=original;}}
test("propietario crea enlace y recibe path",async()=>{const current={id:photoId,owner_user_id:ownerId,public_enabled:false},updated={public_enabled:true,public_token:"token-new",public_revoked_at:null};const result=await mocked([{rows:[current]},{rows:[updated]}],()=>service.updatePublicLink(req,photoId,"photo",false));assert.equal(result.payload.public_link.path,"/public/orangephotos/photo/token-new");});
test("propietario crea enlace de álbum y recibe path",async()=>{const current={id:albumId,owner_user_id:ownerId,public_enabled:false},updated={public_enabled:true,public_token:"album-token-new",public_revoked_at:null};const result=await mocked([{rows:[current]},{rows:[updated]}],()=>service.updatePublicLink(req,albumId,"album",false));assert.equal(result.payload.public_link.path,"/public/orangephotos/album/album-token-new");});
test("segundo POST conserva token",async()=>{const current={id:photoId,owner_user_id:ownerId,public_enabled:true,public_token:"same",public_revoked_at:null};const result=await mocked([{rows:[current]}],()=>service.updatePublicLink(req,photoId,"photo",false));assert.equal(result.payload.public_link.token,"same");});
test("regenerar cambia token",async()=>{const current={id:photoId,owner_user_id:ownerId,public_enabled:true,public_token:"old"},updated={public_enabled:true,public_token:"new",public_revoked_at:null};const result=await mocked([{rows:[current]},{rows:[updated]}],()=>service.updatePublicLink(req,photoId,"photo",true));assert.notEqual(result.payload.public_link.token,"old");});
test("token vacío público devuelve 404 uniforme",async()=>{const result=await service.publicPhotoByToken("   ");assert.equal(result.status,404);assert.equal(result.code,"PUBLIC_NOT_FOUND");});
test("foto inexistente pública devuelve 404 uniforme",async()=>{const result=await mocked([{rows:[]}],()=>service.publicPhotoByToken("missing"));assert.equal(result.status,404);});
test("álbum archivado o token revocado devuelve 404",async()=>{const result=await mocked([{rows:[]}],()=>service.publicAlbumByToken("revoked"));assert.equal(result.status,404);});
test("ZIP rechaza selección vacía",async()=>{const result=await mocked([{rows:[{id:photoId,title:"A",photo_count:0,public_link_active:true}]}],()=>service.publicAlbumDownloadItems("token",[]));assert.equal(result.status,400);});
test("HTTP no accede directamente a PostgreSQL",()=>{const source=fs.readFileSync(path.join(__dirname,"../src/orangePhotosHttp.js"),"utf8");assert.equal(source.includes('require("../db")'),false);});
test("respuesta pública limita campos",()=>{const source=fs.readFileSync(path.join(__dirname,"../src/orangePhotosService.js"),"utf8");for(const field of ["family_id","owner_user_id","object_key","checksum_sha256","exif_json","shared_people"])assert.equal(/PUBLIC_PHOTO_FIELDS=.*$/m.exec(source)?.[0].includes(field),false);});
async function listWithQueries(query,responses=[{rows:[{total:0}]},{rows:[]}]){const original=pool.query,calls=[];let index=0;pool.query=async(sql,values)=>{calls.push({sql,values});return responses[Math.min(index++,responses.length-1)];};try{return{result:await service.list({...req,query}),calls};}finally{pool.query=original;}}
test("filtro de origen incluye por defecto y explícitamente",async()=>{for(const query of [{access_sources:"owned"},{access_sources:"owned",access_sources_mode:"include"}]){const{result,calls}=await listWithQueries(query);assert.equal(result.ok,true);assert.match(calls[0].sql,/p\.owner_user_id=\$2::uuid/);assert.doesNotMatch(calls[0].sql,/NOT \(p\.owner_user_id=\$2::uuid\)/);}});
test("filtro de origen excluye la selección",async()=>{const{result,calls}=await listWithQueries({access_sources:"album",access_sources_mode:"exclude"});assert.equal(result.ok,true);assert.match(calls[0].sql,/NOT \(\(p\.owner_user_id<>\$2::uuid/);});
test("origen vacío en modo exclude no restringe",async()=>{const{result,calls}=await listWithQueries({access_sources:"",access_sources_mode:"exclude"});assert.equal(result.ok,true);assert.doesNotMatch(calls[0].sql,/access_item|direct_share/);});
test("filtro de propietario admite include y exclude",async()=>{for(const mode of ["include","exclude"]){const responses=[{rows:[{id:ownerId}]},{rows:[{total:0}]},{rows:[]}],{result,calls}=await listWithQueries({owner_user_ids:ownerId,owner_user_ids_mode:mode},responses);assert.equal(result.ok,true);assert.match(calls[1].sql,mode==="exclude"?/NOT \(p\.owner_user_id=ANY/:/p\.owner_user_id=ANY/);}});
test("propietarios vacíos en modo exclude no restringen",async()=>{const{result,calls}=await listWithQueries({owner_user_ids:"",owner_user_ids_mode:"exclude"});assert.equal(result.ok,true);assert.doesNotMatch(calls[0].sql,/owner_user_id=ANY/);});
test("modo de filtro desconocido devuelve 400",async()=>{const{result}=await listWithQueries({access_sources_mode:"other"},[]);assert.equal(result.status,400);assert.equal(result.code,"INVALID_FILTER");});
test("propietario externo continúa rechazándose",async()=>{const{result}=await listWithQueries({owner_user_ids:photoId,owner_user_ids_mode:"exclude"},[{rows:[]}]);assert.equal(result.status,400);assert.equal(result.code,"INVALID_FILTER");});
