const test=require("node:test");const assert=require("node:assert/strict");const path=require("node:path");const dbPath=path.resolve(__dirname,"../db.js"),authPath=path.resolve(__dirname,"../src/attachmentsService.js");const calls=[];const pool={query:async()=>({rows:[]})};require.cache[dbPath]={id:dbPath,filename:dbPath,loaded:true,exports:pool};require.cache[authPath]={id:authPath,filename:authPath,loaded:true,exports:{resolveAuthenticatedFamily:req=>req.auth||{ok:false,status:401,code:"NOT_AUTHENTICATED",reason:"No autenticado."}}};const service=require("../src/orangePhotoAlbumAccessService.js");const owner="11111111-1111-4111-8111-111111111111",family="22222222-2222-4222-8222-222222222222",external="33333333-3333-4333-8333-333333333333",album="44444444-4444-4444-8444-444444444444";const req={user:{id:owner},auth:{ok:true,userId:owner,familyId:family}};function mockQueries(...responses){calls.length=0;let index=0;pool.query=async(sql,params)=>{calls.push({sql,params});const response=responses[index++];if(response instanceof Error)throw response;return{rows:response||[]};};}
test("invalid UUID rejects without PostgreSQL",async()=>{mockQueries();const r=await service.resolveOwnedAlbum(req,"bad",pool);assert.equal(r.status,404);assert.equal(calls.length,0);});
test("authentication failure propagates",async()=>{const r=await service.resolveOwnedAlbum({auth:{ok:false,status:401}},album,pool);assert.equal(r.status,401);});
test("missing album returns 404",async()=>{mockQueries([]);assert.equal((await service.resolveOwnedAlbum(req,album,pool)).status,404);});
test("owner album is returned",async()=>{mockQueries([{id:album,family_id:family,owner_user_id:owner,allow_contributions:true,allow_comments:false,is_archived:false}]);const r=await service.resolveOwnedAlbum(req,album,pool);assert.equal(r.payload.album.owner_user_id,owner);assert.equal(calls[0].params[1],family);});
test("unauthenticated access returns 401",async()=>{assert.equal((await service.resolveAlbumAccess({},album,pool)).status,401);});
test("access UUID is validated without query",async()=>{mockQueries();assert.equal((await service.resolveAlbumAccess(req,"bad",pool)).status,404);assert.equal(calls.length,0);});
test("owner has implicit access and all permissions",async()=>{mockQueries([{album_id:album,family_id:family,owner_user_id:owner,allow_contributions:false,allow_comments:false}]);const r=await service.resolveAlbumAccess(req,album,pool);assert.equal(r.payload.isOwner,true);assert.equal(r.payload.subjectType,"owner");assert.deepEqual(r.payload.permissions,{can_view:true,can_contribute:true,can_comment:true});});
test("family and external active ACL retain subject type",async()=>{mockQueries([{album_id:album,family_id:family,owner_user_id:external,allow_contributions:true,allow_comments:true,subject_type:"family"}]);assert.equal((await service.resolveAlbumAccess(req,album,pool)).payload.subjectType,"family");mockQueries([{album_id:album,family_id:family,owner_user_id:external,allow_contributions:true,allow_comments:true,subject_type:"external"}]);assert.equal((await service.resolveAlbumAccess(req,album,pool)).payload.subjectType,"external");});
test("no active access returns 404 and SQL excludes pending/revoked",async()=>{mockQueries([]);assert.equal((await service.resolveAlbumAccess(req,album,pool)).status,404);mockQueries([{album_id:album,family_id:family,owner_user_id:external,allow_contributions:true,allow_comments:true,subject_type:"external"}]);await service.resolveAlbumAccess(req,album,pool);assert.match(calls[0].sql,/access\.status='active'/);assert.match(calls[0].sql,/access\.revoked_at IS NULL/);});
test("common permissions are disabled for non-owner",async()=>{mockQueries([{album_id:album,family_id:family,owner_user_id:external,allow_contributions:false,allow_comments:false,subject_type:"family"}]);const r=await service.resolveAlbumAccess(req,album,pool);assert.equal(r.payload.permissions.can_contribute,false);assert.equal(r.payload.permissions.can_comment,false);});
test("recipients exclude owner and expose family/external statuses",async()=>{mockQueries([{id:album,allow_contributions:true,allow_comments:false}], [], [{user_id:family,email:"f@example.com",display_name:"Familiar",access_status:"active"},{user_id:external,email:"e@example.com",display_name:"Externo",access_status:null}], [{user_id:"55555555-5555-4555-8555-555555555555",email:"pending@example.com",display_name:"Pendiente",access_status:"pending"},{user_id:"66666666-6666-4666-8666-666666666666",email:"revoked@example.com",display_name:"Revocado",access_status:"revoked"}], []);const r=await service.listAlbumRecipients(req,album,pool);assert.equal(r.payload.family.length,2);assert.equal(r.payload.family[0].selected,true);assert.equal(r.payload.family[1].selected,false);assert.equal(r.payload.external[0].selected,true);assert.equal(r.payload.external[1].selected,false);assert.equal(r.payload.album.allow_contributions,true);assert.equal(r.payload.album.allow_comments,false);});
test("external recipient query filters account status",async()=>{mockQueries([{id:album,allow_contributions:false,allow_comments:true}],[],[]);await service.listAlbumRecipients(req,album,pool);assert.match(calls[2].sql,/auth_user\.status IN \('active','pending'\)/);});
const validInput={recipients:[{user_id:external,subject_type:"external",status:"active",invitation_id:null}],allow_contributions:true,allow_comments:false};
function mockTransaction({owned=true,validationRows=[{invalid_count:0}],errorAt=null}={}){calls.length=0;const clientCalls=[];let index=0;const client={query:async(sql,params)=>{clientCalls.push({sql,params});if(errorAt&&clientCalls.length===errorAt)throw new Error("db failure");if(sql==="BEGIN"||sql==="COMMIT"||sql==="ROLLBACK")return{rows:[]};if(clientCalls.length===2)return{rows:owned?[{id:album,family_id:family,owner_user_id:owner,allow_contributions:false,allow_comments:false}]:[]};if(clientCalls.length===3)return{rows:validationRows};return{rows:[]};},release:()=>{clientCalls.released=true;}};pool.connect=async()=>client;return{clientCalls};}
test("rejects missing, unknown, malformed, oversized and non-boolean input before transaction",async()=>{for(const input of [undefined,{recipients:[],allow_contributions:true,allow_comments:false,extra:true},{recipients:"x",allow_contributions:true,allow_comments:false},{recipients:Array.from({length:501},()=>({user_id:external,subject_type:"external",status:"active",invitation_id:null})),allow_contributions:true,allow_comments:false},{recipients:[],allow_contributions:1,allow_comments:false}]){let connected=false;pool.connect=async()=>{connected=true;throw new Error("must not connect")};assert.equal((await service.syncAlbumRecipients(req,album,input,pool)).code,"INVALID_ALBUM_RECIPIENTS");assert.equal(connected,false);}});
test("rejects invalid recipient fields, duplicates and owner",async()=>{for(const recipient of [{user_id:"bad",subject_type:"external",status:"active",invitation_id:null},{user_id:external,subject_type:"other",status:"active",invitation_id:null},{user_id:external,subject_type:"external",status:"waiting",invitation_id:null},{user_id:external,subject_type:"external",status:"pending",invitation_id:null},{user_id:external,subject_type:"family",status:"pending",invitation_id:null},{user_id:external,subject_type:"family",status:"active",invitation_id:external},{user_id:owner,subject_type:"external",status:"active",invitation_id:null}])assert.equal((await service.syncAlbumRecipients(req,album,{...validInput,recipients:[recipient]},pool)).code,"INVALID_ALBUM_RECIPIENTS");assert.equal((await service.syncAlbumRecipients(req,album,{...validInput,recipients:[validInput.recipients[0],validInput.recipients[0]]},pool)).code,"INVALID_ALBUM_RECIPIENTS");});
test("requires transaction capability",async()=>{assert.equal((await service.syncAlbumRecipients(req,album,validInput,{query:async()=>({rows:[]})})).code,"TRANSACTION_UNAVAILABLE");});
test("validates recipients in one transaction query and uses same client for owned album",async()=>{const {clientCalls}=mockTransaction();const result=await service.syncAlbumRecipients(req,album,validInput,pool);assert.equal(result.ok,true);assert.equal(clientCalls[0].sql,"BEGIN");assert.match(clientCalls[1].sql,/orange_photo_albums/);assert.match(clientCalls[2].sql,/jsonb_to_recordset/);assert.equal(clientCalls.filter((call)=>/jsonb_to_recordset/.test(call.sql)).length,3);});
test("validation SQL matches the real membership and invitation schema",async()=>{const {clientCalls}=mockTransaction();await service.syncAlbumRecipients(req,album,validInput,pool);const sql=clientCalls.find((call)=>/invalid_count/.test(call.sql)).sql;assert.match(sql,/membership\.person_id/);assert.match(sql,/family_user\.person_id/);assert.doesNotMatch(sql,/membership\.user_id|m\.user_id/);assert.match(sql,/public\.auth_users/);assert.match(sql,/public\.family_memberships/);assert.match(sql,/membership\.family_id/);assert.match(sql,/membership\.status='active'/);assert.match(sql,/public\.orange_photo_album_guest_invitations/);assert.doesNotMatch(sql,/public\.orange_photo_album_invitations/);});
test("rejects database-invalid family or external recipients and rolls back",async()=>{for(const rows of [[{invalid_count:1}]]){const {clientCalls}=mockTransaction({validationRows:rows});const result=await service.syncAlbumRecipients(req,album,validInput,pool);assert.equal(result.code,"INVALID_ALBUM_RECIPIENTS");assert.equal(clientCalls.at(-1).sql,"ROLLBACK");assert.equal(clientCalls.some((call)=>/UPDATE public\.orange_photo_albums/.test(call.sql)),false);}});
test("updates permissions, upserts recipients and revokes unselected rows",async()=>{const {clientCalls}=mockTransaction();const result=await service.syncAlbumRecipients(req,album,validInput,pool);assert.deepEqual(result.payload,{album_id:album,recipient_count:1,allow_contributions:true,allow_comments:false});assert.match(clientCalls[3].sql,/allow_contributions=\$2/);assert.match(clientCalls[4].sql,/INSERT INTO public\.orange_photo_album_access/);assert.match(clientCalls[4].sql,/ON CONFLICT/);assert.match(clientCalls[5].sql,/status='revoked'/);assert.deepEqual(clientCalls[5].params[1],[external]);assert.equal(clientCalls.at(-1).sql,"COMMIT");});
test("supports family active, external pending and empty revoke set",async()=>{const familyInput={...validInput,recipients:[{user_id:family,subject_type:"family",status:"active",invitation_id:null}]};let tx=mockTransaction();await service.syncAlbumRecipients(req,album,familyInput,pool);assert.match(tx.clientCalls[4].sql,/jsonb_to_recordset/);const invitation="55555555-5555-4555-8555-555555555555";const pending={...validInput,recipients:[{user_id:external,subject_type:"external",status:"pending",invitation_id:invitation}]};tx=mockTransaction();await service.syncAlbumRecipients(req,album,pending,pool);assert.equal(tx.clientCalls[4].params[1],JSON.stringify(pending.recipients));tx=mockTransaction();await service.syncAlbumRecipients(req,album,{...validInput,recipients:[]},pool);assert.deepEqual(tx.clientCalls[5].params[1],[]);});
test("rolls back on SQL error and always releases client",async()=>{const {clientCalls}=mockTransaction({errorAt:4});await assert.rejects(()=>service.syncAlbumRecipients(req,album,validInput,pool));assert.equal(clientCalls.some((call)=>call.sql==="ROLLBACK"),true);assert.equal(clientCalls.released,true);});
test("synchronization SQL writes legacy compatibility but not direct photo shares",async()=>{const {clientCalls}=mockTransaction();await service.syncAlbumRecipients(req,album,validInput,pool);const sql=clientCalls.map((call)=>call.sql).join(" ");assert.match(sql,/orange_photo_album_shares/);assert.match(sql,/orange_photo_album_guest_grants/);assert.doesNotMatch(sql,/orange_photo_shares/);assert.match(sql,/visibility/);assert.doesNotMatch(sql,/DELETE FROM public\.orange_photo_album_guest_grants/);});
test("preserveExternal scopes family ACL, keeps guest grants untouched and honors visibility override",async()=>{const familyInput={recipients:[{user_id:family,subject_type:"family",status:"active",invitation_id:null}],allow_contributions:true,allow_comments:false};const {clientCalls}=mockTransaction();const result=await service.syncAlbumRecipients(req,album,familyInput,pool, {preserveExternal:true,visibilityOverride:"selected"});assert.equal(result.ok,true);const revoke=clientCalls.find(call=>/SET status='revoked'/.test(call.sql)&&/orange_photo_album_access/.test(call.sql));assert.match(revoke.sql,/subject_type='family'/);const visibility=clientCalls.find(call=>/SET visibility=/.test(call.sql));assert.equal(visibility.params[1],"selected");const sql=clientCalls.map(call=>call.sql).join(" ");assert.match(sql,/orange_photo_album_shares/);assert.doesNotMatch(sql,/orange_photo_album_guest_grants/);assert.equal(clientCalls.at(-1).sql,"COMMIT");});
test("listAlbumRecipients devuelve nombres en pending_invitations y permite históricos null",async()=>{mockQueries([{id:album,allow_contributions:false,allow_comments:false}],[],[],[],[{id:"77777777-7777-4777-8777-777777777777",first_name:"Ana",last_name:"García",display_name:"Ana García",email:"ana@example.com",expires_at:new Date(),status:"pending"},{id:"88888888-8888-4888-8888-888888888888",first_name:null,last_name:null,display_name:null,email:"old@example.com",expires_at:new Date(),status:"pending"}]);const result=await service.listAlbumRecipients(req,album,pool);assert.deepEqual(result.payload.pending_invitations.map(item=>item.display_name),["Ana García",null]);assert.equal(result.payload.pending_invitations[1].email,"old@example.com");});
test("ACL incluye guest y filtra module_access",async()=>{mockQueries([{id:album,allow_contributions:false,allow_comments:false}],[],[{user_id:family,role:"guest",email:"guest@example.com",display_name:"Invitado",access_status:null}],[]);const result=await service.listAlbumRecipients(req,album,pool);assert.equal(result.payload.family[0].type,"family");assert.equal(result.payload.family[0].role,"guest");assert.match(calls[2].sql,/role IN \('member','guest'\)/);assert.match(calls[2].sql,/orange_photos/);});
test("validación ACL family exige rol y módulo y mantiene guest válido",async()=>{const {clientCalls}=mockTransaction();const guestInput={...validInput,recipients:[{user_id:family,subject_type:"family",status:"active",invitation_id:null}]};const result=await service.syncAlbumRecipients(req,album,guestInput,pool);const sql=clientCalls.find(call=>/invalid_count/.test(call.sql)).sql;assert.equal(result.ok,true);assert.match(sql,/membership\.role IN \('member','guest'\)/);assert.match(sql,/membership\.module_access ->> 'orange_photos'/);assert.match(sql,/membership\.status='active'/);assert.match(sql,/family_user\.status IN \('active','pending'\)/);assert.match(sql,/recipient\.status='active'/);assert.match(sql,/recipient\.invitation_id IS NULL/);assert.match(sql,/recipient\.user_id<>\$3::uuid/);});
