const test=require("node:test");const assert=require("node:assert/strict");const path=require("node:path");const dbPath=path.resolve(__dirname,"../db.js"),authPath=path.resolve(__dirname,"../src/attachmentsService.js");const calls=[];const pool={query:async()=>({rows:[]})};require.cache[dbPath]={id:dbPath,filename:dbPath,loaded:true,exports:pool};require.cache[authPath]={id:authPath,filename:authPath,loaded:true,exports:{resolveAuthenticatedFamily:req=>req.auth||{ok:false,status:401,code:"NOT_AUTHENTICATED",reason:"No autenticado."}}};const service=require("../src/orangePhotoAlbumAccessService.js");const owner="11111111-1111-4111-8111-111111111111",family="22222222-2222-4222-8222-222222222222",external="33333333-3333-4333-8333-333333333333",album="44444444-4444-4444-8444-444444444444";const req={user:{id:owner},auth:{ok:true,userId:owner,familyId:family}};function mockQueries(...responses){calls.length=0;let index=0;pool.query=async(sql,params)=>{calls.push({sql,params});const response=responses[index++];if(response instanceof Error)throw response;return{rows:response||[]};};}
test("invalid UUID rejects without PostgreSQL",async()=>{mockQueries();const r=await service.resolveOwnedAlbum(req,"bad",pool);assert.equal(r.status,404);assert.equal(calls.length,0);});
test("authentication failure propagates",async()=>{const r=await service.resolveOwnedAlbum({auth:{ok:false,status:401}},album,pool);assert.equal(r.status,401);});
test("missing album returns 404",async()=>{mockQueries([]);assert.equal((await service.resolveOwnedAlbum(req,album,pool)).status,404);});
test("owner album is returned",async()=>{mockQueries([{id:album,family_id:family,owner_user_id:owner,allow_contributions:true,allow_comments:false,is_archived:false}]);const r=await service.resolveOwnedAlbum(req,album,pool);assert.equal(r.payload.album.owner_user_id,owner);assert.equal(calls[0].params[1],family);});
test("unauthenticated access returns 401",async()=>{assert.equal((await service.resolveAlbumAccess({},album,pool)).status,401);});
test("access UUID is validated without query",async()=>{mockQueries();assert.equal((await service.resolveAlbumAccess(req,"bad",pool)).status,404);assert.equal(calls.length,0);});
test("owner has implicit access and all permissions",async()=>{mockQueries([{album_id:album,family_id:family,owner_user_id:owner,allow_contributions:false,allow_comments:false}]);const r=await service.resolveAlbumAccess(req,album,pool);assert.equal(r.payload.isOwner,true);assert.equal(r.payload.subjectType,"owner");assert.deepEqual(r.payload.permissions,{can_view:true,can_contribute:true,can_comment:true});});
test("family and external active ACL retain subject type",async()=>{mockQueries([{album_id:album,family_id:family,owner_user_id:external,allow_contributions:true,allow_comments:true,subject_type:"family"}]);assert.equal((await service.resolveAlbumAccess(req,album,pool)).payload.subjectType,"family");mockQueries([{album_id:album,family_id:family,owner_user_id:external,allow_contributions:true,allow_comments:true,subject_type:"external"}]);assert.equal((await service.resolveAlbumAccess(req,album,pool)).payload.subjectType,"external");});
test("no active access returns 404 and SQL excludes pending/revoked",async()=>{mockQueries([]);assert.equal((await service.resolveAlbumAccess(req,album,pool)).status,404);mockQueries([{album_id:album,family_id:family,owner_user_id:external,allow_contributions:true,allow_comments:true,subject_type:"external"}]);await service.resolveAlbumAccess(req,album,pool);assert.match(calls[0].sql,/access\.status='active'/);assert.match(calls[0].sql,/access\.revoked_at IS NULL/);});
test("common permissions are disabled for non-owner",async()=>{mockQueries([{album_id:album,family_id:family,owner_user_id:external,allow_contributions:false,allow_comments:false,subject_type:"family"}]);const r=await service.resolveAlbumAccess(req,album,pool);assert.equal(r.payload.permissions.can_contribute,false);assert.equal(r.payload.permissions.can_comment,false);});
test("recipients exclude owner and expose family/external statuses",async()=>{mockQueries([{id:album,allow_contributions:true,allow_comments:false}], [{user_id:family,email:"f@example.com",display_name:"Familiar",access_status:"active"},{user_id:external,email:"e@example.com",display_name:"Externo",access_status:null}], [{user_id:"55555555-5555-4555-8555-555555555555",email:"pending@example.com",display_name:"Pendiente",access_status:"pending"},{user_id:"66666666-6666-4666-8666-666666666666",email:"revoked@example.com",display_name:"Revocado",access_status:"revoked"}] );const r=await service.listAlbumRecipients(req,album,pool);assert.equal(r.payload.family.length,2);assert.equal(r.payload.family[0].selected,true);assert.equal(r.payload.family[1].selected,false);assert.equal(r.payload.external[0].selected,true);assert.equal(r.payload.external[1].selected,false);assert.equal(r.payload.album.allow_contributions,true);assert.equal(r.payload.album.allow_comments,false);assert.equal(calls[1].params[2],owner);});
test("external recipient query filters account status",async()=>{mockQueries([{id:album,allow_contributions:false,allow_comments:true}],[],[]);await service.listAlbumRecipients(req,album,pool);assert.match(calls[2].sql,/auth_user\.status IN \('active','pending'\)/);});
