/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { IonIcon } from "@ionic/react";
import { chevronBackOutline, chevronForwardOutline, informationCircleOutline } from "ionicons/icons";
import { OD_ICONS } from "../ui/odIcons.js";

const ZOOM_MIN = .25, ZOOM_MAX = 4, ZOOM_STEP = 1.25;
export default function AttachmentsImageLightbox({ viewer, onClose, onPrevious, onNext, hasPrevious = false, hasNext = false, renderInfo, infoOpen = false, onToggleInfo, renderExtraActions }) {
  const [userZoom, setUserZoom] = useState(1), [natural, setNatural] = useState({ w: 0, h: 0 }), [viewport, setViewport] = useState({ w: 0, h: 0 });
  const stageRef = useRef(null);
  const center = useCallback(() => { if (stageRef.current) { stageRef.current.scrollLeft = 0; stageRef.current.scrollTop = 0; } }, []);
  const resetView = useCallback(() => { setUserZoom(1); center(); }, [center]);
  const close = useCallback(() => { resetView(); onClose?.(); }, [onClose, resetView]);
  const move = useCallback(direction => { setNatural({ w: 0, h: 0 }); resetView(); direction === "previous" ? onPrevious?.() : onNext?.(); }, [onNext, onPrevious, resetView]);
  useEffect(() => { const element = stageRef.current; if (!element) return; const observer = new ResizeObserver(([entry]) => setViewport({ w: entry.contentRect.width, h: entry.contentRect.height })); observer.observe(element); return () => observer.disconnect(); }, [infoOpen]);
  useEffect(() => { if (!viewer) return; setNatural({ w: 0, h: 0 }); resetView(); }, [viewer?.url, resetView]);
  useEffect(() => { const key = event => { if (event.key === "Escape") { if (infoOpen) onToggleInfo?.(); else close(); } else if (event.key === "ArrowLeft" && hasPrevious) move("previous"); else if (event.key === "ArrowRight" && hasNext) move("next"); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [close, hasPrevious, hasNext, infoOpen, move, onToggleInfo]);
  const size = useMemo(() => { if (!natural.w || !natural.h || !viewport.w || !viewport.h) return null; const fit = Math.min(Math.max(120, viewport.w - 48) / natural.w, Math.max(120, viewport.h - 48) / natural.h, 1); return { width: Math.round(natural.w * fit * userZoom), height: Math.round(natural.h * fit * userZoom) }; }, [natural, viewport, userZoom]);
  if (!viewer || typeof document === "undefined") return null;
  const title = viewer.title || viewer.filename || "Imagen", isVideo = viewer.mediaType === "video" || viewer.media_type === "video", zoomTitle = `${Math.round(userZoom * 100)}%`;
  return createPortal(<div className={`od-attachments-lightbox${infoOpen ? " is-info-open" : ""}`} role="dialog" aria-modal="true" aria-label={title}><div className="od-attachments-lightbox__toolbar"><p className="od-attachments-lightbox__title">{viewer.positionLabel || title}</p><div className="od-attachments-lightbox__controls">{renderExtraActions?.()}{!isVideo ? <><button type="button" className="od-attachments-lightbox__btn" aria-label="Reducir zoom" title={`Reducir zoom (${zoomTitle})`} onClick={() => setUserZoom(value => Math.max(value / ZOOM_STEP, ZOOM_MIN))}><IonIcon icon={OD_ICONS.richDivider} /></button><button type="button" className="od-attachments-lightbox__btn" aria-label="Ampliar zoom" title={`Ampliar zoom (${zoomTitle})`} onClick={() => setUserZoom(value => Math.min(value * ZOOM_STEP, ZOOM_MAX))}><IonIcon icon={OD_ICONS.add} /></button><button type="button" className="od-attachments-lightbox__btn" aria-label="Ajustar a pantalla" title="Ajustar a pantalla" onClick={resetView}><IonIcon icon={OD_ICONS.expandSections} /></button></> : null}{renderInfo ? <button type="button" className={`od-attachments-lightbox__btn${infoOpen ? " is-active" : ""}`} aria-label="Información" title="Información" onClick={onToggleInfo}><IonIcon icon={informationCircleOutline} /></button> : null}<button type="button" className="od-attachments-lightbox__btn od-attachments-lightbox__btn--close" aria-label="Cerrar" title="Cerrar" onClick={close}><IonIcon icon={OD_ICONS.bulkExit} /></button></div></div><button type="button" className="od-attachments-lightbox__nav od-attachments-lightbox__nav--previous" aria-label="Anterior" disabled={!hasPrevious} onClick={() => move("previous")}><IonIcon icon={chevronBackOutline} /></button>{infoOpen && renderInfo ? <aside className="od-attachments-lightbox__info"><header><h2>Información</h2><button type="button" className="od-attachments-lightbox__btn" aria-label="Cerrar información" title="Cerrar información" onClick={onToggleInfo}><IonIcon icon={OD_ICONS.bulkExit} /></button></header>{renderInfo()}</aside> : null}<div ref={stageRef} className="od-attachments-lightbox__stage">{isVideo ? <video className="od-attachments-lightbox__video" src={viewer.url} poster={viewer.poster || undefined} controls preload="metadata" /> : <img src={viewer.url} alt={title} className="od-attachments-lightbox__img" style={size || undefined} onLoad={event => setNatural({ w: event.currentTarget.naturalWidth, h: event.currentTarget.naturalHeight })} />}</div><button type="button" className="od-attachments-lightbox__nav od-attachments-lightbox__nav--next" aria-label="Siguiente" disabled={!hasNext} onClick={() => move("next")}><IonIcon icon={chevronForwardOutline} /></button></div>, document.body);
}
