const { createHash, randomBytes } = require("node:crypto");
const pool = require("../db");
const photos = require("./orangePhotosService");
const { resolveAuthenticatedFamily } = require("./attachmentsService");
const { getSignedOrangePhotoUrl } = require("./wasabiClient");
const { createSecureToken, hashToken } = require("./auth");
const { sendActivationEmail, sendAlbumGuestInvitationEmail } = require("./mailService");
const ok = photos.ok; const bad = photos.bad;
const uuid = value => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(value || ""));
const hashGuestInvitationToken = token => createHash("sha256").update(token, "utf8").digest("hex");
const createGuestInvitationToken = () => randomBytes(32).toString("base64url");
const rollbackBad = async (client, result) => { await client.query("ROLLBACK").catch(() => {}); return result; };
async function createActivationToken(queryable, userId) { const token = createSecureToken(); await queryable.query(`UPDATE public.auth_activation_tokens SET used_at=now() WHERE user_id=$1::uuid AND used_at IS NULL`, [userId]); await queryable.query(`INSERT INTO public.auth_activation_tokens(user_id,token_hash,expires_at) VALUES($1::uuid,$2,now()+interval '48 hours')`, [userId, hashToken(token)]); return token; }
async function owner(req, albumId, queryable = pool) { const auth=resolveAuthenticatedFamily(req); if(!auth.ok)return auth; if(!uuid(albumId))return bad(404,"ALBUM_NOT_FOUND","Álbum no encontrado."); const row=(await queryable.query(`SELECT id,title,family_id FROM public.orange_photo_albums WHERE id=$1::uuid AND owner_user_id=$2::uuid AND family_id=$3::uuid AND is_archived=false`,[albumId,auth.userId,auth.familyId])).rows[0]; return row?ok({auth,album:row}):bad(404,"ALBUM_NOT_FOUND","Álbum no encontrado."); }
async function resolveGuestAlbumAccess(req,albumId){if(!req.user?.id)return bad(401,"NOT_AUTHENTICATED","No autenticado.");if(!uuid(albumId))return bad(404,"ALBUM_NOT_FOUND","Álbum no encontrado.");const row=(await pool.query(`SELECT a.id,g.can_view,g.can_contribute,g.can_comment FROM public.orange_photo_album_guest_grants g JOIN public.orange_photo_albums a ON a.id=g.album_id AND a.is_archived=false WHERE g.album_id=$1::uuid AND g.user_id=$2::uuid AND g.status='active' AND g.revoked_at IS NULL AND g.can_view=true`,[albumId,req.user.id])).rows[0];return row?{ok:true,userId:String(req.user.id),albumId,grant:{can_view:row.can_view,can_contribute:row.can_contribute,can_comment:row.can_comment}}:bad(404,"GUEST_ACCESS_DENIED","Álbum no encontrado.");}
async function createInvitation(req,albumId,body={}){const o=await owner(req,albumId);if(!o.ok)return o;const firstName=String(body.first_name||"").trim(),lastName=String(body.last_name||"").trim(),email=String(body.email||"").trim().toLowerCase();if(!firstName||firstName.length>100)return bad(400,"INVALID_FIRST_NAME","El nombre no es válido.");if(!lastName||lastName.length>150)return bad(400,"INVALID_LAST_NAME","Los apellidos no son válidos.");if(!email||email.length>320||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return bad(400,"INVALID_EMAIL","Email no válido.");const me=(await pool.query(`SELECT email FROM public.auth_users WHERE id=$1::uuid`,[req.user.id])).rows[0];if(me&&String(me.email).trim().toLowerCase()===email)return bad(400,"CANNOT_INVITE_SELF","No puedes invitarte a ti mismo.");const member=(await pool.query(`SELECT u.id FROM public.auth_users u JOIN public.family_memberships fm ON fm.person_id=u.person_id AND fm.family_id=$2::uuid AND fm.status='active' WHERE lower(btrim(u.email))=$1`,[email,o.payload.album.family_id])).rows[0];if(member)return bad(409,"FAMILY_MEMBER_GUEST","Los miembros familiares no se invitan como externos.");const existing=(await pool.query(`SELECT 1 FROM public.orange_photo_album_guest_grants g JOIN public.auth_users u ON u.id=g.user_id WHERE g.album_id=$1::uuid AND lower(btrim(u.email))=$2 AND g.status='active'`,[albumId,email])).rows[0];if(existing)return bad(409,"GUEST_ALREADY_GRANTED","El invitado ya tiene acceso.");const token=createGuestInvitationToken();try{const row=(await pool.query(`INSERT INTO public.orange_photo_album_guest_invitations(album_id,invited_first_name,invited_last_name,invited_email,invited_by_user_id,token_hash,can_contribute,can_comment,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,now()+interval '7 days') RETURNING id,invited_first_name first_name,invited_last_name last_name,invited_email email,concat_ws(' ',invited_first_name,invited_last_name) display_name,can_view,can_contribute,can_comment,status,expires_at`,[albumId,firstName,lastName,email,req.user.id,hashGuestInvitationToken(token),body.can_contribute===true,body.can_comment===true])).rows[0];return ok({invitation:{...row,accept_path:`/guest-invitations/${token}`}});}catch(e){if(e.code==='23505')return bad(409,"INVITATION_ALREADY_PENDING","Ya existe una invitación pendiente.");throw e;}}
async function listAccess(req,albumId){const o=await owner(req,albumId);if(!o.ok)return o;await pool.query(`UPDATE public.orange_photo_album_guest_invitations SET status='expired' WHERE album_id=$1 AND status='pending' AND revoked_at IS NULL AND expires_at<=now()`,[albumId]);const [i,g]=await Promise.all([pool.query(`SELECT id,invited_email email,can_view,can_contribute,can_comment,status,expires_at FROM public.orange_photo_album_guest_invitations WHERE album_id=$1 AND status='pending' AND revoked_at IS NULL AND expires_at>now() ORDER BY created_at DESC`,[albumId]),pool.query(`SELECT g.id,g.user_id,u.email,COALESCE(NULLIF(btrim(p.preferred_name),''),btrim(concat_ws(' ',p.first_name,p.last_name)),u.email) display_name,g.can_view,g.can_contribute,g.can_comment,g.status,g.created_at FROM public.orange_photo_album_guest_grants g JOIN public.auth_users u ON u.id=g.user_id LEFT JOIN public.persons p ON p.id=u.person_id WHERE g.album_id=$1 AND g.status='active' ORDER BY g.created_at DESC`,[albumId])]);return ok({pending_invitations:i.rows,grants:g.rows});}
async function publicInvitation(token){const row=(await pool.query(`SELECT i.invited_first_name first_name,i.invited_last_name last_name,NULLIF(btrim(concat_ws(' ',i.invited_first_name,i.invited_last_name)),'') display_name,i.invited_email email,i.can_view,i.can_contribute,i.can_comment,i.expires_at,a.title,COALESCE(NULLIF(btrim(p.preferred_name),''),btrim(concat_ws(' ',p.first_name,p.last_name)),u.email) owner_display_name FROM public.orange_photo_album_guest_invitations i JOIN public.orange_photo_albums a ON a.id=i.album_id AND a.is_archived=false JOIN public.auth_users u ON u.id=a.owner_user_id LEFT JOIN public.persons p ON p.id=u.person_id WHERE i.token_hash=$1 AND i.status='pending' AND i.revoked_at IS NULL AND i.expires_at>now()`,[hashGuestInvitationToken(String(token||""))])).rows[0];return row?ok({invitation:row}):bad(404,"INVITATION_NOT_FOUND","Invitación no encontrada.");}
async function accept(req,token){if(!req.user?.id)return bad(401,"NOT_AUTHENTICATED","No autenticado.");const client=await pool.connect();try{await client.query("BEGIN");const i=(await client.query(`SELECT i.*,a.title,a.is_archived FROM public.orange_photo_album_guest_invitations i JOIN public.orange_photo_albums a ON a.id=i.album_id WHERE i.token_hash=$1 FOR UPDATE`,[hashGuestInvitationToken(String(token||""))])).rows[0];if(!i||i.status!=="pending"||i.revoked_at||new Date(i.expires_at).getTime()<=Date.now()||i.is_archived)return rollbackBad(client,bad(404,"INVITATION_NOT_FOUND","Invitación no encontrada."));const u=(await client.query(`SELECT email,status FROM public.auth_users WHERE id=$1::uuid`,[req.user.id])).rows[0];if(!u||u.status!=="active"||String(u.email).trim().toLowerCase()!==i.invited_email)return rollbackBad(client,bad(403,"INVITATION_EMAIL_MISMATCH","La invitación está dirigida a otra dirección de correo."));const existing=(await client.query(`SELECT id,status FROM public.orange_photo_album_guest_grants WHERE album_id=$1 AND user_id=$2 FOR UPDATE`,[i.album_id,req.user.id])).rows[0];if(existing?.status==='active')return rollbackBad(client,bad(409,"GUEST_ALREADY_GRANTED","El invitado ya tiene acceso."));if(existing)await client.query(`UPDATE public.orange_photo_album_guest_grants SET invitation_id=$1,can_view=$2,can_contribute=$3,can_comment=$4,status='active',revoked_at=NULL,granted_by_user_id=$5,updated_at=now() WHERE id=$6`,[i.id,i.can_view,i.can_contribute,i.can_comment,i.invited_by_user_id,existing.id]);else await client.query(`INSERT INTO public.orange_photo_album_guest_grants(album_id,user_id,invitation_id,can_contribute,can_comment,granted_by_user_id) VALUES($1,$2,$3,$4,$5,$6)`,[i.album_id,req.user.id,i.id,i.can_contribute,i.can_comment,i.invited_by_user_id]);await client.query(`UPDATE public.orange_photo_album_guest_invitations SET status='accepted',accepted_at=now(),accepted_by_user_id=$2 WHERE id=$1`,[i.id,req.user.id]);await client.query(`INSERT INTO public.orange_photo_album_access(album_id,user_id,subject_type,status,invitation_id,created_by_user_id,accepted_at,revoked_at,created_at,updated_at) VALUES($1::uuid,$2::uuid,'external','active',$3::uuid,$4::uuid,now(),NULL,now(),now()) ON CONFLICT (album_id,user_id) DO UPDATE SET subject_type='external',status='active',invitation_id=EXCLUDED.invitation_id,created_by_user_id=EXCLUDED.created_by_user_id,accepted_at=COALESCE(public.orange_photo_album_access.accepted_at,EXCLUDED.accepted_at),revoked_at=NULL,updated_at=now()`,[i.album_id,req.user.id,i.id,i.invited_by_user_id]);await client.query("COMMIT");return ok({album:{id:i.album_id,title:i.title},grant:{can_view:i.can_view,can_contribute:i.can_contribute,can_comment:i.can_comment},redirect_path:`/guest/orangephotos/albums/${i.album_id}`});}catch(e){await client.query("ROLLBACK").catch(()=>{});throw e;}finally{client.release();}}
async function guestAlbums(req){if(!req.user?.id)return bad(401,"NOT_AUTHENTICATED","No autenticado.");const rows=(await pool.query(`SELECT a.id,a.title,COALESCE(NULLIF(btrim(p.preferred_name),''),btrim(concat_ws(' ',p.first_name,p.last_name)),u.email) owner_display_name,(SELECT count(*)::int FROM public.orange_photo_album_items ai JOIN public.orange_photos ph ON ph.id=ai.photo_id WHERE ai.album_id=a.id AND ph.is_trashed=false) photo_count,g.can_view,g.can_contribute,g.can_comment FROM public.orange_photo_album_guest_grants g JOIN public.orange_photo_albums a ON a.id=g.album_id AND a.is_archived=false JOIN public.auth_users u ON u.id=a.owner_user_id LEFT JOIN public.persons p ON p.id=u.person_id WHERE g.user_id=$1 AND g.status='active' AND g.revoked_at IS NULL AND g.can_view=true ORDER BY a.title`,[req.user.id])).rows;return ok({items:rows});}
async function guestAlbum(req,id){const access=await resolveGuestAlbumAccess(req,id);if(!access.ok)return access;const row=(await pool.query(`SELECT a.id,a.title,a.description,COALESCE(NULLIF(btrim(p.preferred_name),''),btrim(concat_ws(' ',p.first_name,p.last_name)),u.email) owner_display_name,(SELECT count(*)::int FROM public.orange_photo_album_items WHERE album_id=a.id) photo_count FROM public.orange_photo_albums a JOIN public.auth_users u ON u.id=a.owner_user_id LEFT JOIN public.persons p ON p.id=u.person_id WHERE a.id=$1`,[id])).rows[0];return ok({album:row,permissions:access.grant});}
const publicPhotoFields=["id","media_type","original_filename","mime_type","title","description","captured_at","captured_at_source","width","height","duration_seconds","orientation","camera_make","camera_model","lens_model","latitude","longitude","altitude_meters","location_name","location_country","location_region","location_locality","created_at","updated_at","owner_display_name"];
const MAX_GUEST_ZIP_ITEMS=500;
async function guestPhotos(req,id,q={}){const access=await resolveGuestAlbumAccess(req,id);if(!access.ok)return access;const page=Math.max(1,Number(q.page)||1),per=Math.min(100,Math.max(1,Number(q.per_page)||100)),base=`FROM public.orange_photo_album_items ai JOIN public.orange_photos p ON p.id=ai.photo_id AND p.is_trashed=false JOIN public.auth_users u ON u.id=p.owner_user_id LEFT JOIN public.persons pe ON pe.id=u.person_id WHERE ai.album_id=$1::uuid`,total=Number((await pool.query(`SELECT count(*)::int total ${base}`,[id])).rows[0].total),rows=(await pool.query(`SELECT p.id,p.media_type,p.original_filename,p.mime_type,p.title,p.description,p.captured_at,p.captured_at_source,p.width,p.height,p.duration_seconds,p.orientation,p.camera_make,p.camera_model,p.lens_model,p.latitude,p.longitude,p.altitude_meters,p.location_name,p.location_country,p.location_region,p.location_locality,p.created_at,p.updated_at,COALESCE(NULLIF(btrim(pe.preferred_name),''),btrim(concat_ws(' ',pe.first_name,pe.last_name)),u.email) owner_display_name,f.bucket AS _bucket,f.object_key AS _object_key,f.variant AS _variant ${base} LEFT JOIN public.orange_photo_files f ON f.photo_id=p.id AND f.variant IN ('original','thumbnail','preview','poster') ORDER BY p.captured_at DESC NULLS LAST,p.created_at DESC,p.id DESC LIMIT $2 OFFSET $3`,[id,per,(page-1)*per])).rows;const grouped=new Map();for(const row of rows){const key=String(row.id);if(!grouped.has(key))grouped.set(key,{row,files:{}});if(row._variant)grouped.get(key).files[row._variant]={bucket:row._bucket,object_key:row._object_key};}const items=await Promise.all([...grouped.values()].map(async ({row,files})=>{const item=Object.fromEntries(publicPhotoFields.map(field=>[field,row[field]??null]));for(const [variant,file] of Object.entries(files)){const url=await getSignedOrangePhotoUrl(file);if(variant==='original')item.original_url=url;if(variant==='thumbnail')item.thumbnail_url=url;if(variant==='preview')item.preview_url=url;if(variant==='poster')item.poster_url=url;}return item;}));return ok({items,page,per_page:per,total,has_more:page*per<total});}
async function guestPhotoDownload(req,albumId,photoId){const access=await resolveGuestAlbumAccess(req,albumId);if(!access.ok)return access;if(!uuid(photoId))return bad(404,"PHOTO_NOT_FOUND","Foto no encontrada.");const row=(await pool.query(`SELECT p.id,p.original_filename,p.mime_type,f.bucket,f.object_key FROM public.orange_photo_album_items ai JOIN public.orange_photos p ON p.id=ai.photo_id AND p.is_trashed=false JOIN public.orange_photo_files f ON f.photo_id=p.id AND f.variant='original' WHERE ai.album_id=$1::uuid AND ai.photo_id=$2::uuid LIMIT 1`,[albumId,photoId])).rows[0];if(!row)return bad(404,"PHOTO_NOT_FOUND","Foto no encontrada.");return ok({download:{url:await getSignedOrangePhotoUrl({bucket:row.bucket,object_key:row.object_key}),filename:row.original_filename||"archivo",mime_type:row.mime_type||"application/octet-stream"}});}
async function revokeInvitation(req,albumId,id){const o=await owner(req,albumId);if(!o.ok)return o;if(!uuid(id))return bad(404,"INVITATION_NOT_FOUND","Invitación no encontrada.");const row=(await pool.query(`UPDATE public.orange_photo_album_guest_invitations SET status='revoked',revoked_at=now() WHERE id=$1 AND album_id=$2 AND status='pending' RETURNING id`,[id,albumId])).rows[0];return row?ok({revoked:true}):bad(404,"INVITATION_NOT_FOUND","Invitación no encontrada.");}
async function revokeGrant(req,albumId,id){if(!uuid(id))return bad(404,"GUEST_GRANT_NOT_FOUND","Acceso no encontrado.");const client=await pool.connect();let transactionStarted=false;try{await client.query("BEGIN");transactionStarted=true;const o=await owner(req,albumId,client);if(!o.ok){await client.query("ROLLBACK");return o;}const row=(await client.query(`UPDATE public.orange_photo_album_guest_grants SET status='revoked',revoked_at=now() WHERE id=$1 AND album_id=$2 AND status='active' RETURNING id,user_id`,[id,albumId])).rows[0];if(!row){await client.query("ROLLBACK");return bad(404,"GUEST_GRANT_NOT_FOUND","Acceso no encontrado.");}await client.query(`UPDATE public.orange_photo_album_access SET status='revoked',revoked_at=now(),updated_at=now() WHERE album_id=$1::uuid AND user_id=$2::uuid AND subject_type='external' AND status<>'revoked'`,[albumId,row.user_id]);await client.query("COMMIT");return ok({revoked:true});}catch(e){if(transactionStarted)await client.query("ROLLBACK").catch(()=>{});throw e;}finally{client.release();}}
async function listFamilyExternalGuests(req){const auth=resolveAuthenticatedFamily(req);if(!auth.ok)return auth;const family=req.user?.families?.find(item=>String(item.id)===String(auth.familyId));if(family?.role!=="owner")return bad(403,"OWNER_REQUIRED","Solo el administrador puede consultar los invitados externos.");const result=await pool.query(`SELECT g.user_id,u.email,COALESCE(NULLIF(btrim(p.preferred_name),''),NULLIF(btrim(concat_ws(' ',p.first_name,p.last_name)),''),u.email) display_name,u.status auth_status,count(*)::int album_count,json_agg(json_build_object('grant_id',g.id,'album_id',a.id,'album_title',a.title,'can_view',g.can_view,'can_contribute',g.can_contribute,'can_comment',g.can_comment,'granted_at',g.created_at) ORDER BY a.title,a.id) albums FROM public.orange_photo_album_guest_grants g JOIN public.orange_photo_albums a ON a.id=g.album_id AND a.family_id=$1::uuid AND a.is_archived=false JOIN public.auth_users u ON u.id=g.user_id LEFT JOIN public.persons p ON p.id=u.person_id WHERE g.status='active' AND g.revoked_at IS NULL AND g.can_view=true GROUP BY g.user_id,u.email,u.status,p.preferred_name,p.first_name,p.last_name ORDER BY lower(COALESCE(NULLIF(btrim(p.preferred_name),''),NULLIF(btrim(concat_ws(' ',p.first_name,p.last_name)),''),u.email)),g.user_id`,[auth.familyId]);return ok({items:result.rows.map(row=>({user_id:String(row.user_id),email:row.email,display_name:row.display_name,auth_status:row.auth_status,album_count:Number(row.album_count||0),albums:Array.isArray(row.albums)?row.albums:[]}))});}
async function createInvitation(req, albumId, body = {}) {
  const o = await owner(req, albumId); if (!o.ok) return o;
  const firstName = String(body.first_name || "").trim(), lastName = String(body.last_name || "").trim(), email = String(body.email || "").trim().toLowerCase();
  if (!firstName || firstName.length > 100) return bad(400, "INVALID_FIRST_NAME", "El nombre no es válido.");
  if (!lastName || lastName.length > 150) return bad(400, "INVALID_LAST_NAME", "Los apellidos no son válidos.");
  if (!email || email.length > 320 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return bad(400, "INVALID_EMAIL", "Email no válido.");
  const me = (await pool.query(`SELECT email FROM public.auth_users WHERE id=$1::uuid`, [req.user.id])).rows[0];
  if (me && String(me.email).trim().toLowerCase() === email) return bad(400, "CANNOT_INVITE_SELF", "No puedes invitarte a ti mismo.");
  const member = (await pool.query(`SELECT u.id FROM public.auth_users u JOIN public.family_memberships fm ON fm.person_id=u.person_id AND fm.family_id=$2::uuid AND fm.status='active' WHERE lower(btrim(u.email))=$1`, [email, o.payload.album.family_id])).rows[0];
  if (member) return bad(409, "FAMILY_MEMBER_GUEST", "Los miembros familiares no se invitan como externos.");
  const existingGrant = (await pool.query(`SELECT 1 FROM public.orange_photo_album_guest_grants g JOIN public.auth_users u ON u.id=g.user_id WHERE g.album_id=$1::uuid AND lower(btrim(u.email))=$2 AND g.status='active'`, [albumId, email])).rows[0];
  if (existingGrant) return bad(409, "GUEST_ALREADY_GRANTED", "El invitado ya tiene acceso.");
  const client = await pool.connect(); let guestToken; let activationToken = null; let accountMode; let invitation; let targetUser; let invitationSent = false; let mailOmitted = false;
  try {
    await client.query("BEGIN");
    const account = (await client.query(`SELECT u.id AS user_id,u.person_id,u.email,u.status,u.password_hash,u.email_verified,p.first_name,p.last_name FROM public.auth_users u LEFT JOIN public.persons p ON p.id=u.person_id WHERE lower(btrim(u.email))=$1 LIMIT 1 FOR UPDATE OF u`, [email])).rows[0];
    if (account && ["disabled", "locked"].includes(account.status)) return rollbackBad(client, bad(409, "GUEST_ACCOUNT_UNAVAILABLE", "La cuenta asociada a este email no está disponible."));
    if (!account) {
      const person = (await client.query(`INSERT INTO public.persons(first_name,last_name) VALUES($1,$2) RETURNING id`, [firstName, lastName])).rows[0];
      targetUser = (await client.query(`INSERT INTO public.auth_users(person_id,email,status,password_hash,email_verified) VALUES($1::uuid,$2,'pending',NULL,false) RETURNING id,person_id,email,status`, [person.id, email])).rows[0];
      activationToken = await createActivationToken(client, targetUser.id); accountMode = "created";
    } else { targetUser = account; if (account.status === "pending") { await client.query(`UPDATE public.persons SET first_name=CASE WHEN NULLIF(btrim(first_name),'') IS NULL THEN $2 ELSE first_name END,last_name=CASE WHEN NULLIF(btrim(last_name),'') IS NULL THEN $3 ELSE last_name END WHERE id=$1::uuid`, [account.person_id, firstName, lastName]); activationToken = await createActivationToken(client, account.user_id); accountMode = "pending"; } else { accountMode = "active"; } }
    guestToken = createGuestInvitationToken();
    const row = (await client.query(`INSERT INTO public.orange_photo_album_guest_invitations(album_id,invited_first_name,invited_last_name,invited_email,invited_by_user_id,token_hash,can_contribute,can_comment,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,now()+interval '7 days') RETURNING id,invited_first_name first_name,invited_last_name last_name,invited_email email,concat_ws(' ',invited_first_name,invited_last_name) display_name,can_view,can_contribute,can_comment,status,expires_at`, [albumId, firstName, lastName, email, req.user.id, hashGuestInvitationToken(guestToken), body.can_contribute === true, body.can_comment === true])).rows[0];
    invitation = { ...row, accept_path: `/guest-invitations/${guestToken}` }; await client.query("COMMIT");
  } catch (error) { await client.query("ROLLBACK").catch(() => {}); throw error; } finally { client.release(); }
  try {
    const ownerRow = (await pool.query(`SELECT COALESCE(NULLIF(btrim(p.preferred_name),''),NULLIF(btrim(concat_ws(' ',p.first_name,p.last_name)),''),u.email) AS display_name FROM public.auth_users u LEFT JOIN public.persons p ON p.id=u.person_id WHERE u.id=$1::uuid`, [req.user.id])).rows[0];
    const displayName = [firstName, lastName].filter(Boolean).join(" ");
    const delivery = accountMode === "active" ? await sendAlbumGuestInvitationEmail({ to: email, displayName, ownerDisplayName: ownerRow?.display_name || req.user.email || "OrangeFamily", albumTitle: o.payload.album.title, invitationPath: invitation.accept_path }) : await sendActivationEmail({ to: email, displayName, token: activationToken, returnTo: invitation.accept_path });
    invitationSent = delivery.sent === true; mailOmitted = delivery.omitted === true;
  } catch (mailError) { console.error("Album guest invitation email failed:", mailError.message); }
  return { ok: true, status: 201, payload: { invitation, delivery: { sent: invitationSent, omitted: mailOmitted, account_mode: accountMode } } };
}

async function resendInvitation(req, albumId, invitationId) {
  const o = await owner(req, albumId); if (!o.ok) return o; if (!uuid(invitationId)) return bad(404, "INVITATION_NOT_FOUND", "Invitación no encontrada.");
  const client = await pool.connect(); let item; let accountMode; let activationToken = null; let guestToken;
  try { await client.query("BEGIN"); item = (await client.query(`SELECT i.id,i.album_id,i.invited_first_name,i.invited_last_name,i.invited_email,i.status,i.expires_at,a.title AS album_title FROM public.orange_photo_album_guest_invitations i JOIN public.orange_photo_albums a ON a.id=i.album_id WHERE i.id=$1::uuid AND i.album_id=$2::uuid AND i.status='pending' AND i.revoked_at IS NULL AND i.expires_at>now() LIMIT 1 FOR UPDATE`, [invitationId, albumId])).rows[0]; if (!item) return rollbackBad(client, bad(404, "INVITATION_NOT_FOUND", "Invitación no encontrada.")); const user = (await client.query(`SELECT id,status FROM public.auth_users WHERE lower(btrim(email))=$1 LIMIT 1 FOR UPDATE`, [item.invited_email])).rows[0]; if (!user || ["disabled", "locked"].includes(user.status)) return rollbackBad(client, bad(409, "GUEST_ACCOUNT_UNAVAILABLE", "La cuenta asociada a este email no está disponible.")); accountMode = user.status === "active" ? "active" : "pending"; if (accountMode === "pending") activationToken = await createActivationToken(client, user.id); guestToken = createGuestInvitationToken(); await client.query(`UPDATE public.orange_photo_album_guest_invitations SET token_hash=$1,expires_at=now()+interval '7 days' WHERE id=$2::uuid`, [hashGuestInvitationToken(guestToken), invitationId]); await client.query("COMMIT"); } catch (error) { await client.query("ROLLBACK").catch(() => {}); throw error; } finally { client.release(); }
  try { const delivery = accountMode === "active" ? await sendAlbumGuestInvitationEmail({ to: item.invited_email, displayName: [item.invited_first_name, item.invited_last_name].filter(Boolean).join(" "), ownerDisplayName: o.payload.album.title, albumTitle: item.album_title, invitationPath: `/guest-invitations/${guestToken}` }) : await sendActivationEmail({ to: item.invited_email, displayName: [item.invited_first_name, item.invited_last_name].filter(Boolean).join(" "), token: activationToken, returnTo: `/guest-invitations/${guestToken}` }); return ok({ invitation_sent: delivery.sent === true, mail_omitted: delivery.omitted === true }); } catch (error) { console.error("Album guest invitation email failed:", error.message); return ok({ invitation_sent: false, mail_omitted: false }); }
}

async function guestPhotosPaged(req, id, q = {}) {
  const access = await resolveGuestAlbumAccess(req, id); if (!access.ok) return access;
  const page = Math.max(1, Number(q.page) || 1), per = Math.min(100, Math.max(1, Number(q.per_page) || 100));
  const fromBase = `FROM public.orange_photo_album_items ai JOIN public.orange_photos p ON p.id=ai.photo_id AND p.is_trashed=false`;
  const whereBase = `WHERE ai.album_id=$1::uuid`;
  const total = Number((await pool.query(`SELECT count(*)::int AS total ${fromBase} ${whereBase}`, [id])).rows[0].total);
  const rows = (await pool.query(`WITH page_photos AS (SELECT p.id ${fromBase} ${whereBase} ORDER BY p.captured_at DESC NULLS LAST,p.created_at DESC,p.id DESC LIMIT $2 OFFSET $3) SELECT p.id,p.media_type,p.original_filename,p.mime_type,p.title,p.description,p.captured_at,p.captured_at_source,p.width,p.height,p.duration_seconds,p.orientation,p.camera_make,p.camera_model,p.lens_model,p.latitude,p.longitude,p.altitude_meters,p.location_name,p.location_country,p.location_region,p.location_locality,p.created_at,p.updated_at,COALESCE(NULLIF(btrim(pe.preferred_name),''),btrim(concat_ws(' ',pe.first_name,pe.last_name)),u.email) owner_display_name,f.bucket AS _bucket,f.object_key AS _object_key,f.variant AS _variant FROM page_photos page JOIN public.orange_photos p ON p.id=page.id JOIN public.auth_users u ON u.id=p.owner_user_id LEFT JOIN public.persons pe ON pe.id=u.person_id LEFT JOIN public.orange_photo_files f ON f.photo_id=p.id AND f.variant IN ('original','thumbnail','preview','poster') ORDER BY p.captured_at DESC NULLS LAST,p.created_at DESC,p.id DESC,f.variant`, [id, per, (page - 1) * per])).rows;
  const grouped = new Map(); for (const row of rows) { const key = String(row.id); if (!grouped.has(key)) grouped.set(key, { row, files: {} }); if (row._variant) grouped.get(key).files[row._variant] = { bucket: row._bucket, object_key: row._object_key }; }
  const items = await Promise.all([...grouped.values()].map(async ({ row, files }) => { const item = Object.fromEntries(publicPhotoFields.map(field => [field, row[field] ?? null])); for (const [variant, file] of Object.entries(files)) { const url = await getSignedOrangePhotoUrl(file); if (variant === "original") item.original_url = url; if (variant === "thumbnail") item.thumbnail_url = url; if (variant === "preview") item.preview_url = url; if (variant === "poster") item.poster_url = url; } return item; }));
  return ok({ items, page, per_page: per, total, has_more: page * per < total });
}

async function guestDownloadItems(req, albumId, body = {}) { const access = await resolveGuestAlbumAccess(req, albumId); if (!access.ok) return access; const rawIds = Array.isArray(body.photo_ids) ? body.photo_ids : []; const photoIds = [...new Set(rawIds.map(value => String(value || "").trim()))]; if (!photoIds.length || photoIds.length > MAX_GUEST_ZIP_ITEMS || photoIds.some(value => !uuid(value))) return bad(400, "INVALID_PHOTO_SELECTION", "Selecciona entre 1 y 500 elementos válidos."); const rows = (await pool.query(`SELECT p.id,p.original_filename,p.mime_type,f.bucket,f.object_key FROM public.orange_photo_album_items ai JOIN public.orange_photos p ON p.id=ai.photo_id AND p.is_trashed=false JOIN public.orange_photo_files f ON f.photo_id=p.id AND f.variant='original' WHERE ai.album_id=$1::uuid AND p.id=ANY($2::uuid[])`, [albumId, photoIds])).rows; if (rows.length !== photoIds.length) return bad(404, "PHOTO_NOT_FOUND", "Alguno de los elementos no pertenece al álbum."); const byId = new Map(rows.map(row => [String(row.id), row])); return ok({ items: photoIds.map(photoId => byId.get(photoId)) }); }
async function downloadGuestObject(item) { return photos.downloadObject(item); }

async function listGuestOwnedPhotos(req, query = {}) {
  if (!req.user?.id) return bad(401, "NOT_AUTHENTICATED", "No autenticado.");
  const family = Array.isArray(req.user.families) ? req.user.families[0] : null;
  if (family?.role !== "guest" || family?.module_access?.orange_photos !== true) return bad(403, "GUEST_ROLE_REQUIRED", "Acceso no permitido.");
  const page = Math.max(1, Number.parseInt(query.page, 10) || 1);
  const perPage = Math.min(100, Math.max(1, Number.parseInt(query.per_page, 10) || 30));
  const offset = (page - 1) * perPage;
  const sql = `WITH accessible AS (SELECT DISTINCT ai.photo_id, min(ai.album_id) OVER (PARTITION BY ai.photo_id) AS accessible_album_id FROM public.orange_photo_album_items ai JOIN public.orange_photo_album_access acl ON acl.album_id=ai.album_id AND acl.user_id=$1::uuid AND acl.subject_type='family' AND acl.status='active' AND acl.revoked_at IS NULL JOIN public.orange_photo_albums album ON album.id=ai.album_id AND album.is_archived=false), filtered AS (SELECT photo.*, accessible.accessible_album_id FROM public.orange_photos photo JOIN accessible ON accessible.photo_id=photo.id WHERE photo.owner_user_id=$1::uuid AND photo.is_trashed=false) SELECT filtered.*,count(*) OVER()::integer AS total_count FROM filtered ORDER BY COALESCE(filtered.captured_at,filtered.created_at) DESC,filtered.id DESC LIMIT $2 OFFSET $3`;
  const rows = (await pool.query(sql, [req.user.id, perPage, offset])).rows;
  const items = await Promise.all(rows.map(async row => { const item = Object.fromEntries(publicPhotoFields.map(field => [field, row[field] ?? null])); item.accessible_album_id = row.accessible_album_id; item.is_owned_by_current_user = true; const files = (await pool.query(`SELECT bucket,object_key,variant FROM public.orange_photo_files WHERE photo_id=$1::uuid AND variant IN ('original','thumbnail','preview','poster')`, [row.id])).rows; for(const file of files){const url=await getSignedOrangePhotoUrl(file);if(file.variant==="original")item.original_url=url;if(file.variant==="thumbnail")item.thumbnail_url=url;if(file.variant==="preview")item.preview_url=url;if(file.variant==="poster")item.poster_url=url;} return item; }));
  const total = Number(rows[0]?.total_count || 0);
  return ok({ items, page, per_page: perPage, total, has_more: offset + items.length < total });
}

module.exports={createGuestInvitationToken,hashGuestInvitationToken,resolveGuestAlbumAccess,createInvitation,resendInvitation,listAccess,revokeInvitation,revokeGrant,publicInvitation,accept,guestAlbums,guestAlbum,guestPhotos:guestPhotosPaged,guestPhotoDownload,guestDownloadItems,downloadGuestObject,listFamilyExternalGuests,listGuestOwnedPhotos};
