const { createHash, randomBytes } = require("node:crypto");
const pool = require("../db");
const photos = require("./orangePhotosService");
const { resolveAuthenticatedFamily } = require("./attachmentsService");
const tokenHash = token => createHash("sha256").update(token, "utf8").digest("hex");
const createGuestInvitationToken = () => randomBytes(32).toString("base64url");
const ok = photos.ok, bad = photos.bad;
function uuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||""));}
async function owner(req, albumId){const a=resolveAuthenticatedFamily(req);if(!a.ok)return a;if(!uuid(albumId))return bad(404,"ALBUM_NOT_FOUND","Álbum no encontrado.");const r=await pool.query(`SELECT id,title,owner_user_id,is_archived,family_id FROM public.orange_photo_albums WHERE id=$1::uuid AND owner_user_id=$2::uuid AND is_archived=false AND family_id=$3::uuid`,[albumId,a.userId,a.familyId]);return r.rows[0]?ok({auth:a,album:r.rows[0]}):bad(404,"ALBUM_NOT_FOUND","Álbum no encontrado.");}
async function resolveGuestAlbumAccess(req,albumId){if(!req.user?.id)return bad(401,"NOT_AUTHENTICATED","No autenticado.");const r=await pool.query(`SELECT a.id,g.can_view,g.can_contribute,g.can_comment FROM public.orange_photo_album_guest_grants g JOIN public.orange_photo_albums a ON a.id=g.album_id AND a.is_archived=false WHERE g.album_id=$1::uuid AND g.user_id=$2::uuid AND g.status='active' AND g.revoked_at IS NULL AND g.can_view=true`,[albumId,req.user.id]);return r.rows[0]?{ok:true,userId:String(req.user.id),albumId,grant:{can_view:r.rows[0].can_view,can_contribute:r.rows[0].can_contribute,can_comment:r.rows[0].can_comment}}:bad(404,"GUEST_ACCESS_DENIED","Álbum no encontrado.");}
async function createInvitation(req,albumId,body={}){const o=await owner(req,albumId);if(!o.ok)return o;const email=String(body.email||"").trim().toLowerCase();if(!email||email.length>320||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return bad(400,"INVALID_EMAIL","Email no válido.");const flags={can_contribute:body.can_contribute===true,can_comment:body.can_comment===true};const target=await pool.query(`SELECT u.id FROM public.auth_users u JOIN public.family_memberships fm ON fm.person_id=u.person_id AND fm.family_id=$2::uuid AND fm.status='active' WHERE lower(btrim(u.email))=$1`,[email,o.album.family_id]);if(target.rows.length)return bad(409,"FAMILY_MEMBER_GUEST","Los miembros familiares no se invitan como externos.");const existing=await pool.query(`SELECT 1 FROM public.orange_photo_album_guest_grants g JOIN public.auth_users u ON u.id=g.user_id WHERE g.album_id=$1::uuid AND lower(btrim(u.email))=$2 AND g.status='active'`,[albumId,email]);if(existing.rows.length)return bad(409,"GUEST_ALREADY_GRANTED","El invitado ya tiene acceso.");const token=createGuestInvitationToken();try{const r=await pool.query(`INSERT INTO public.orange_photo_album_guest_invitations(album_id,invited_email,invited_by_user_id,token_hash,can_contribute,can_comment,expires_at) VALUES($1::uuid,$2,$3::uuid,$4,$5,$6,now()+interval '7 days') RETURNING id,invited_email,can_view,can_contribute,can_comment,status,expires_at`,[albumId,email,req.user.id,tokenHash(token),flags.can_contribute,flags.can_comment]);return ok({invitation:{...r.rows[0],email:r.rows[0].invited_email,accept_path:`/guest-invitations/${token}`}});}catch(e){if(e.code==='23505')return bad(409,"INVITATION_ALREADY_PENDING","Ya existe una invitación pendiente.");throw e;}}
async function listAccess(req,albumId){const o=await owner(req,albumId);if(!o.ok)return o;const [i,g]=await Promise.all([pool.query(`SELECT id,invited_email email,can_view,can_contribute,can_comment,status,expires_at FROM public.orange_photo_album_guest_invitations WHERE album_id=$1::uuid AND status='pending' AND revoked_at IS NULL ORDER BY created_at DESC`,[albumId]),pool.query(`SELECT g.id,g.user_id,u.email,COALESCE(NULLIF(btrim(p.preferred_name),''),btrim(concat_ws(' ',p.first_name,p.last_name)),u.email) display_name,g.can_view,g.can_contribute,g.can_comment,g.status,g.created_at FROM public.orange_photo_album_guest_grants g JOIN public.auth_users u ON u.id=g.user_id LEFT JOIN public.persons p ON p.id=u.person_id WHERE g.album_id=$1::uuid AND g.status='active' ORDER BY g.created_at DESC`,[albumId])]);return ok({pending_invitations:i.rows,grants:g.rows});}
async function publicInvitation(token){const r=await pool.query(`SELECT i.invited_email email,i.can_view,i.can_contribute,i.can_comment,i.expires_at,a.title,COALESCE(NULLIF(btrim(p.preferred_name),''),btrim(concat_ws(' ',p.first_name,p.last_name)),u.email) owner_display_name FROM public.orange_photo_album_guest_invitations i JOIN public.orange_photo_albums a ON a.id=i.album_id AND a.is_archived=false JOIN public.auth_users u ON u.id=a.owner_user_id LEFT JOIN public.persons p ON p.id=u.person_id WHERE i.token_hash=$1 AND i.status='pending' AND i.revoked_at IS NULL AND i.expires_at>now()`,[tokenHash(String(token||""))]);return r.rows[0]?ok({invitation:r.rows[0]}):bad(404,"INVITATION_NOT_FOUND","Invitación no encontrada.");}
async function accept(req,token){if(!req.user?.id)return bad(401,"NOT_AUTHENTICATED","No autenticado.");const c=await pool.connect();try{await c.query('BEGIN');const r=await c.query(`SELECT i.*,a.title,a.is_archived FROM public.orange_photo_album_guest_invitations i JOIN public.orange_photo_albums a ON a.id=i.album_id WHERE i.token_hash=$1 FOR UPDATE`,[tokenHash(String(token||""))]);const i=r.rows[0];if(!i||i.status!=='pending'||i.revoked_at||new Date(i.expires_at)<=new Date()||i.is_archived)return bad(404,"INVITATION_NOT_FOUND","Invitación no encontrada.");const u=await c.query(`SELECT email,status FROM public.auth_users WHERE id=$1::uuid`,[req.user.id]);if(!u.rows[0]||u.rows[0].status!=='active'||String(u.rows[0].email).trim().toLowerCase()!==i.invited_email)return bad(403,"INVITATION_EMAIL_MISMATCH","La invitación está dirigida a otra dirección de correo.");await c.query(`INSERT INTO public.orange_photo_album_guest_grants(album_id,user_id,invitation_id,can_contribute,can_comment,granted_by_user_id) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(album_id,user_id) DO UPDATE SET status='active',revoked_at=NULL,can_contribute=EXCLUDED.can_contribute,can_comment=EXCLUDED.can_comment`,[i.album_id,req.user.id,i.id,i.can_contribute,i.can_comment,i.invited_by_user_id]);await c.query(`UPDATE public.orange_photo_album_guest_invitations SET status='accepted',accepted_at=now(),accepted_by_user_id=$2 WHERE id=$1`,[i.id,req.user.id]);await c.query('COMMIT');return ok({album:{id:i.album_id,title:i.title},grant:{can_view:i.can_view,can_contribute:i.can_contribute,can_comment:i.can_comment},redirect_path:`/guest/orangephotos/albums/${i.album_id}`});}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
async function guestAlbums(req){if(!req.user?.id)return bad(401,"NOT_AUTHENTICATED","No autenticado.");const r=await pool.query(`SELECT a.id,a.title,COALESCE(NULLIF(btrim(p.preferred_name),''),btrim(concat_ws(' ',p.first_name,p.last_name)),u.email) owner_display_name,(SELECT count(*)::int FROM public.orange_photo_album_items ai JOIN public.orange_photos ph ON ph.id=ai.photo_id WHERE ai.album_id=a.id AND ph.is_trashed=false) photo_count,g.can_view,g.can_contribute,g.can_comment FROM public.orange_photo_album_guest_grants g JOIN public.orange_photo_albums a ON a.id=g.album_id AND a.is_archived=false JOIN public.auth_users u ON u.id=a.owner_user_id LEFT JOIN public.persons p ON p.id=u.person_id WHERE g.user_id=$1::uuid AND g.status='active' AND g.revoked_at IS NULL AND g.can_view=true ORDER BY a.title`,[req.user.id]);return ok({items:r.rows});}
async function guestAlbum(req,id){const a=await resolveGuestAlbumAccess(req,id);if(!a.ok)return a;const r=await pool.query(`SELECT a.id,a.title,a.description,COALESCE(NULLIF(btrim(p.preferred_name),''),btrim(concat_ws(' ',p.first_name,p.last_name)),u.email) owner_display_name,(SELECT count(*)::int FROM public.orange_photo_album_items WHERE album_id=a.id) photo_count FROM public.orange_photo_albums a JOIN public.auth_users u ON u.id=a.owner_user_id LEFT JOIN public.persons p ON p.id=u.person_id WHERE a.id=$1::uuid`,[id]);return ok({album:r.rows[0],permissions:a.grant});}
async function guestPhotos(req,id,q={}){const a=await resolveGuestAlbumAccess(req,id);if(!a.ok)return a;const page=Math.max(1,Number(q.page)||1),per=Math.min(100,Math.max(1,Number(q.per_page)||100)),base=`FROM public.orange_photo_album_items ai JOIN public.orange_photos p ON p.id=ai.photo_id JOIN public.auth_users u ON u.id=p.owner_user_id LEFT JOIN public.persons pe ON pe.id=u.person_id WHERE ai.album_id=$1::uuid AND p.is_trashed=false`,total=Number((await pool.query(`SELECT count(*)::int total ${base}`,[id])).rows[0].total),rows=(await pool.query(`SELECT p.*,COALESCE(NULLIF(btrim(pe.preferred_name),''),btrim(concat_ws(' ',pe.first_name,pe.last_name)),u.email) owner_display_name ${base} ORDER BY p.captured_at DESC NULLS LAST,p.created_at DESC,p.id DESC LIMIT $2 OFFSET $3`,[id,per,(page-1)*per])).rows;await photos.applyStoredImageMetadata?.(rows);return ok({items:rows,page,per_page:per,total,has_more:page*per<total});}
async function revokeInvitation(req,albumId,id){const o=await owner(req,albumId);if(!o.ok)return o;const r=await pool.query(`UPDATE public.orange_photo_album_guest_invitations SET status='revoked',revoked_at=now() WHERE id=$1::uuid AND album_id=$2::uuid AND status='pending' RETURNING id`,[id,albumId]);return r.rows[0]?ok({revoked:true}):bad(404,"INVITATION_NOT_FOUND","Invitación no encontrada.");}
async function revokeGrant(req,albumId,id){const o=await owner(req,albumId);if(!o.ok)return o;const r=await pool.query(`UPDATE public.orange_photo_album_guest_grants SET status='revoked',revoked_at=now() WHERE id=$1::uuid AND album_id=$2::uuid AND status='active' RETURNING id`,[id,albumId]);return r.rows[0]?ok({revoked:true}):bad(404,"GUEST_GRANT_NOT_FOUND","Acceso no encontrado.");}
module.exports={createGuestInvitationToken,hashGuestInvitationToken:tokenHash,resolveGuestAlbumAccess,createInvitation,listAccess,revokeInvitation,revokeGrant,publicInvitation,accept,guestAlbums,guestAlbum,guestPhotos};
