import { useState } from "react";
import { IonApp, IonButton, IonContent, IonIcon, IonInput, IonItem, IonLabel, IonList, IonPage, IonText } from "@ionic/react";
import { eyeOffOutline, eyeOutline } from "ionicons/icons";
import { useAuth } from "./authContext.js";
import { postForgotPassword } from "../shared/api/authApi.js";
import "./app-login.css";

export default function LoginPage() {
  const { login } = useAuth(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(""); const [forgot, setForgot] = useState(false); const [notice, setNotice] = useState(() => new URLSearchParams(window.location.search).get("auth_message") || "");
  async function handleSubmit(e) { e.preventDefault(); setError(""); setSubmitting(true); try { await login(email, password); } catch (loginError) { setError(loginError instanceof Error ? loginError.message : "No se pudo iniciar sesión."); } finally { setSubmitting(false); } }
  async function handleForgot(e) { e.preventDefault(); setError(""); setSubmitting(true); try { setNotice((await postForgotPassword(email)).message); } catch (forgotError) { setError(forgotError.message); } finally { setSubmitting(false); } }
  return <IonApp><IonPage className="od-login-page"><IonContent fullscreen scrollY={false} className="od-login-page__content"><div className="od-login-page__split"><div className="od-login-page__form-side"><div className="od-login-page__form-stack"><div className="od-login-page__card"><h1 className="od-login-page__title">OrangeFamily</h1><p className="od-login-page__subtitle">{forgot ? "Solicita un enlace de recuperación" : "Inicia sesión para continuar"}</p><form onSubmit={forgot ? handleForgot : handleSubmit} className="od-login-page__form"><IonList className="od-login-page__list" lines="full"><IonItem className="od-login-page__item"><IonLabel position="stacked">Email</IonLabel><IonInput type="email" autoComplete="username" inputMode="email" value={email} required disabled={submitting} onIonInput={(e) => setEmail(String(e.detail.value || ""))} /></IonItem>{!forgot ? <IonItem className="od-login-page__item od-login-page__item--password"><IonLabel position="stacked">Contraseña</IonLabel><IonInput type={showPassword ? "text" : "password"} autoComplete="current-password" value={password} required disabled={submitting} onIonInput={(e) => setPassword(String(e.detail.value || ""))} /><IonButton slot="end" fill="clear" type="button" className="od-login-page__toggle-password" aria-label={showPassword ? "Ocultar contraseña" : "Mostrar contraseña"} onClick={() => setShowPassword((v) => !v)}><IonIcon icon={showPassword ? eyeOffOutline : eyeOutline} /></IonButton></IonItem> : null}</IonList>{notice ? <p className="od-login-page__notice">{notice}</p> : null}{error ? <IonText color="danger" role="alert"><p className="od-login-page__error">{error}</p></IonText> : null}<IonButton type="submit" expand="block" className="od-login-page__submit" disabled={submitting}>{submitting ? "Procesando…" : forgot ? "Enviar enlace" : "Entrar"}</IonButton><button type="button" className="od-login-page__forgot" onClick={() => { setForgot((v) => !v); setError(""); setNotice(""); }}>{forgot ? "Volver al inicio de sesión" : "He olvidado mi contraseña"}</button></form></div></div></div><div className="od-login-page__brand-side" aria-hidden="true" /></div></IonContent></IonPage></IonApp>;
}
