import { useEffect, useState } from "react";
import { useAuth } from "../../app/authContext.js";
import { getLatestAndroidRelease, updateLatestAndroidRelease } from "./appReleasesApi.js";
import "./settings.css";
export default function DownloadsPage() {
  const { user } = useAuth(); const isOwner = user?.families?.some((family) => family.role === "owner");
  const [release, setRelease] = useState(null); const [error, setError] = useState("");
  useEffect(() => { getLatestAndroidRelease().then((data) => setRelease(data.release || null)).catch((e) => setError(e.message)); }, []);
  return <div className="od-page"><div className="od-page-inner"><h1 className="od-page-title">Ajustes · Descargas</h1>{error && <p className="od-status-line od-status-line--error">{error}</p>}{!release ? <p className="od-status-line">Todavía no hay una versión Android publicada.</p> : <section className="od-card"><h2>OrangeFamily Photos Sync</h2><p>Versión {release.version_name} · código {release.version_code}</p><p>Archivo: {release.file_name}</p><a className="od-modal-primary-link" href={release.download_url} target="_blank" rel="noreferrer">Descargar APK</a></section>}<section className="od-card"><h2>Instalación y actualización</h2><p>Descarga el APK y ábrelo desde el navegador o Archivos. La web no puede confirmar de forma fiable si el agente está instalado.</p></section>{isOwner && <ReleaseForm release={release} onSaved={setRelease} />}</div></div>;
}
function ReleaseForm({ release, onSaved }) { const [form, setForm] = useState({ version_code: release?.version_code || "", version_name: release?.version_name || "", file_name: release?.file_name || "", download_url: release?.download_url || "", release_notes: release?.release_notes || "" }); const set = (key) => (event) => setForm({ ...form, [key]: event.target.value }); return <form className="od-card" onSubmit={async (event) => { event.preventDefault(); const data = await updateLatestAndroidRelease({ ...form, version_code: Number(form.version_code) }); onSaved(data.release); }}><h2>Publicación Android</h2>{["version_code","version_name","file_name","download_url","release_notes"].map((key) => <label className="od-form-field" key={key}>{key}<input className="od-filter-input" value={form[key]} onChange={set(key)} required={key !== "release_notes"} /></label>)}<button className="od-modal-primary" type="submit">Guardar publicación</button></form>; }
