import { useEffect, useState } from "react";
import { IonBadge, IonButton } from "@ionic/react";
import { createFamilyMember, listFamilyMembers, resendInvitation, sendMemberPasswordReset, updateFamilyMember } from "./familyMembersApi.js";
import "./familyMembers.css";

const emptyForm = { first_name: "", last_name: "", email: "", has_access: true, membership_status: "active" };

export default function FamilyMembersPage() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [editing, setEditing] = useState(null); const [form, setForm] = useState(emptyForm); const [saving, setSaving] = useState(false);
  async function load() { setLoading(true); setError(""); try { setItems((await listFamilyMembers()).items || []); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  function openCreate() { setEditing("new"); setForm(emptyForm); setMessage(""); }
  function openEdit(item) { setEditing(item.person_id); setForm({ first_name: item.first_name, last_name: item.last_name || "", email: item.email || "", has_access: item.has_access, membership_status: item.membership_status }); setMessage(""); }
  async function submit(event) { event.preventDefault(); setSaving(true); setError(""); try { const body = { first_name: form.first_name, last_name: form.last_name, email: form.email, has_access: form.has_access }; if (editing !== "new") body.membership_status = form.membership_status; const result = editing === "new" ? await createFamilyMember(body) : await updateFamilyMember(editing, body); setMessage(result.invitation_sent === false ? "Familiar guardado, pero la invitación no pudo enviarse." : "Familiar guardado."); setEditing(null); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } }
  async function action(callback, success) { setError(""); setMessage(""); try { await callback(); setMessage(success); await load(); } catch (e) { setError(e.message); } }
  return <div className="od-page"><div className="od-page-inner od-page-inner--full od-page-inner--align-stretch">
    <div className="od-page-header"><div><h1 className="od-page-title">Ajustes · Familiares</h1><p className="od-page-subtitle">Los familiares con acceso pueden utilizar OrangePhotos.</p></div><IonButton className="od-modal-primary" onClick={openCreate}>Añadir familiar</IonButton></div>
    <nav className="of-settings-links" aria-label="Ajustes"><a href="/app/settings/family">Familiares</a><a href="/app/settings/attachments">Attachments</a></nav>
    {error ? <p className="od-status-line od-status-line--error" role="alert">{error}</p> : null}{message ? <p className="od-status-line">{message}</p> : null}
    {editing ? <form className="of-family-form" onSubmit={submit}><div className="of-family-form__grid">
      <label className="od-form-field"><span className="od-form-label">Nombre *</span><input className="od-filter-input" required maxLength="120" value={form.first_name} onChange={(e) => setForm({ ...form, first_name: e.target.value })} /></label>
      <label className="od-form-field"><span className="od-form-label">Apellidos</span><input className="od-filter-input" maxLength="160" value={form.last_name} onChange={(e) => setForm({ ...form, last_name: e.target.value })} /></label>
      <label className="od-form-field"><span className="od-form-label">Email</span><input className="od-filter-input" type="email" required={form.has_access} value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label>
      {editing !== "new" ? <label className="od-form-field"><span className="od-form-label">Estado</span><select className="od-filter-select" value={form.membership_status} onChange={(e) => setForm({ ...form, membership_status: e.target.value })}><option value="active">Activo</option><option value="inactive">Inactivo</option></select></label> : null}
    </div><label className="of-family-form__check"><input type="checkbox" checked={form.has_access} onChange={(e) => setForm({ ...form, has_access: e.target.checked })} /> Permitir acceso a OrangeFamily</label><div className="od-modal-actions"><button type="button" className="od-button-secondary" onClick={() => setEditing(null)}>Cancelar</button><button type="submit" className="od-modal-primary" disabled={saving}>{saving ? "Guardando…" : "Guardar"}</button></div></form> : null}
    {loading ? <p className="od-status-line">Cargando familiares…</p> : <div className="od-table-wrap"><table className="od-table od-table--fill"><thead><tr><th>Nombre</th><th>Email</th><th>Rol</th><th>Acceso</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{items.map((item) => <tr key={item.person_id}><td>{[item.first_name,item.last_name].filter(Boolean).join(" ")}</td><td>{item.email || "—"}</td><td><IonBadge className="od-badge od-badge--style-1">{item.role === "owner" ? "Administrador" : "Familiar"}</IonBadge></td><td>{item.has_access ? "Sí" : "No"}</td><td>{item.membership_status === "active" ? "Activo" : "Inactivo"}{item.auth_status ? ` · ${item.auth_status}` : ""}</td><td>{item.role === "owner" ? "—" : <div className="of-family-actions"><button className="od-button-secondary" onClick={() => openEdit(item)}>Editar</button>{item.auth_status === "pending" ? <button className="od-button-secondary" onClick={() => void action(() => resendInvitation(item.person_id), "Invitación procesada.")}>Reenviar invitación</button> : null}{item.auth_status === "active" ? <button className="od-button-secondary" onClick={() => void action(() => sendMemberPasswordReset(item.person_id), "Recuperación solicitada.")}>Recuperar contraseña</button> : null}</div>}</td></tr>)}</tbody></table></div>}
  </div></div>;
}
