import { useState } from "react";
import { createOrangeAlbumGuestInvitation } from "./orangeGuestAlbumApi.js";

export default function OrangeAlbumGuestInviteModal({ album, allowContributions = false, allowComments = false, onClose, onChanged }) {
  const [email, setEmail] = useState("");
  const [state, setState] = useState({ busy: false, error: "", path: "" });
  const [copyFeedback, setCopyFeedback] = useState("");
  const invitationUrl = state.path ? `${window.location.origin}${state.path}` : "";
  const submit = async event => { event.preventDefault(); if (state.busy || state.path) return; setState({ busy: true, error: "", path: "" }); try { const result = await createOrangeAlbumGuestInvitation(album.id, { email, can_contribute: allowContributions, can_comment: allowComments }); setState({ busy: false, error: "", path: result.invitation.accept_path }); onChanged?.(); } catch (inviteError) { setState({ busy: false, error: inviteError.message, path: "" }); } };
  const copyInvitation = async () => { try { await navigator.clipboard.writeText(invitationUrl); setCopyFeedback("Enlace copiado"); } catch { setCopyFeedback("No se pudo copiar el enlace."); } };
  return <div className="od-modal-backdrop"><section className="od-modal" role="dialog" aria-modal="true"><header className="od-modal-header"><h2 className="od-modal-title">Invitar persona externa</h2><button className="od-modal-close" type="button" disabled={state.busy} onClick={onClose}>×</button></header>{state.path ? <div className="od-modal-body"><p>Invitación creada. Comparte este enlace:</p><div className="od-orangephotos-guest-invitation-url">{invitationUrl}</div><button className="od-button-secondary" type="button" onClick={copyInvitation}>Copiar invitación</button>{copyFeedback ? <p className="od-orangephotos-guest-copy-feedback" role="status">{copyFeedback}</p> : null}<div className="od-modal-actions"><button className="od-btn od-btn-primary" type="button" onClick={onClose}>Cerrar</button></div></div> : <form className="od-modal-body" onSubmit={submit}><label className="od-form-field"><span className="od-form-label">Email</span><input className="od-filter-input" type="email" required value={email} disabled={state.busy} onChange={event => setEmail(event.target.value)} /></label><p className="od-inline-msg">Se aplicarán los permisos comunes actuales del álbum.</p>{state.error ? <p className="od-status-line od-status-line--error">{state.error}</p> : null}<div className="od-modal-actions"><button className="od-btn od-btn-secondary" type="button" disabled={state.busy} onClick={onClose}>Cancelar</button><button className="od-btn od-btn-primary" type="submit" disabled={state.busy}>{state.busy ? "Creando…" : "Crear invitación"}</button></div></form>}</section></div>;
}
