const DB_NAME="orangefamily",DB_VERSION=1,STORE="orange_photo_upload_queue";
const RUNNING=new Set(["checking","uploading","verifying"]);

function openDb(){return new Promise((resolve,reject)=>{if(!globalThis.indexedDB)return reject(new Error("IndexedDB no disponible."));const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:"key"});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error("No se pudo abrir IndexedDB."));});}
async function transaction(mode,work){const db=await openDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode),store=tx.objectStore(STORE);let result;try{result=work(store);}catch(error){reject(error);return;}tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error||new Error("No se pudo actualizar la cola persistente."));tx.onabort=()=>reject(tx.error||new Error("Se canceló la actualización de la cola."));});}finally{db.close();}}
export async function loadUploadQueue(){const rows=await transaction("readonly",store=>new Promise((resolve,reject)=>{const request=store.getAll();request.onsuccess=()=>resolve(request.result||[]);request.onerror=()=>reject(request.error);}));return rows.map(item=>{const file=item.file&&!(item.file instanceof File)?new File([item.file],item.filename,{type:item.mimeType,lastModified:item.lastModified||Date.now()}):item.file;return{...item,file,status:!file?"missing_file":RUNNING.has(item.status)?"paused":item.status,message:!file?"Es necesario volver a seleccionar el archivo":RUNNING.has(item.status)?"Subida pausada":item.message};});}
export const putUploadQueueItem=item=>transaction("readwrite",store=>store.put({...item,updatedAt:new Date().toISOString()}));
export const putUploadQueueItems=items=>transaction("readwrite",store=>{for(const item of items)store.put({...item,updatedAt:new Date().toISOString()});});
export const deleteUploadQueueItem=key=>transaction("readwrite",store=>store.delete(key));
export const clearTerminalUploadQueue=()=>transaction("readwrite",store=>new Promise((resolve,reject)=>{const request=store.openCursor();request.onsuccess=()=>{const cursor=request.result;if(!cursor)return resolve();if(["completed","cancelled","error","missing_file","duplicate_pending"].includes(cursor.value.status))cursor.delete();cursor.continue();};request.onerror=()=>reject(request.error);}));
