import { useRef, useState } from "react";
import { IonIcon } from "@ionic/react";
import { arrowUndoOutline, checkboxOutline, heart, heartOutline, shareSocialOutline } from "ionicons/icons";
import AttachmentsImageLightbox from "../../shared/components/AttachmentsImageLightbox.jsx";
import { orangePhotoDownloadUrl } from "../../shared/api/orangePhotosApi.js";
import { OD_ICONS } from "../../shared/ui/odIcons.js";
import OrangePhotoDetailsPanel from "./OrangePhotoDetailsPanel.jsx";
import OrangePhotoShareModal from "./OrangePhotoShareModal.jsx";

export default function OrangePhotoViewer({ photo, members, selected, trashMode, onToggleSelected, onToggleFavorite, onClose, onSave, onShareSave, onTrash, onRestore, onPurge, onPrevious, onNext, hasPrevious, hasNext, positionLabel }) {
  const [infoOpen, setInfoOpen] = useState(false), [shareOpen, setShareOpen] = useState(false), [feedback, setFeedback] = useState(""), shareButtonRef = useRef(null);
  const displayTitle = photo.title?.trim() || photo.original_filename?.trim() || "Sin título";
  const notify = message => { setFeedback(message); window.setTimeout(() => setFeedback(""), 2000); };
  const save = async body => { setFeedback("Guardando…"); try { await onSave(body); notify("Cambios guardados"); } catch (error) { setFeedback(error.message); } };
  return <><AttachmentsImageLightbox viewer={{ url: photo.original_url || photo.preview_url || photo.thumbnail_url, poster: photo.poster_url || photo.thumbnail_url, mediaType: photo.media_type, title: displayTitle, positionLabel }} onClose={onClose} onPrevious={onPrevious} onNext={onNext} hasPrevious={hasPrevious} hasNext={hasNext} infoOpen={infoOpen} onToggleInfo={() => setInfoOpen(open => !open)} renderInfo={() => <OrangePhotoDetailsPanel photo={photo} members={members} onSave={save} feedback={feedback} />} renderExtraActions={() => <>{!trashMode ? <><button className={`od-attachments-lightbox__btn${selected ? " is-selected" : ""}`} type="button" aria-label={selected ? "Quitar de la selección" : "Añadir a la selección"} title={selected ? "Quitar de la selección" : "Añadir a la selección"} onClick={onToggleSelected}><IonIcon icon={checkboxOutline} /></button><button className={`od-attachments-lightbox__btn${photo.is_favorite ? " is-active" : ""}`} type="button" aria-label={photo.is_favorite ? "Quitar de favoritas" : "Añadir a favoritas"} title={photo.is_favorite ? "Quitar de favoritas" : "Añadir a favoritas"} onClick={onToggleFavorite}><IonIcon icon={photo.is_favorite ? heart : heartOutline} /></button><button ref={shareButtonRef} className={`od-attachments-lightbox__btn${photo.visibility !== "private" ? " is-active" : ""}`} type="button" aria-label="Compartir" title="Compartir" onClick={() => setShareOpen(true)}><IonIcon icon={shareSocialOutline} /></button><a className="od-attachments-lightbox__btn" href={orangePhotoDownloadUrl(photo.id)} aria-label="Descargar" title="Descargar"><IonIcon icon={OD_ICONS.export} /></a></> : null}{trashMode && photo.is_owner ? <><button className="od-attachments-lightbox__btn" type="button" aria-label="Restaurar" title="Restaurar" onClick={onRestore}><IonIcon icon={arrowUndoOutline} /></button><button className="od-attachments-lightbox__btn od-attachments-lightbox__btn--danger" type="button" aria-label="Eliminar definitivamente" title="Eliminar definitivamente" onClick={onPurge}><IonIcon icon={OD_ICONS.delete} /></button></> : photo.is_owner ? <button className="od-attachments-lightbox__btn od-attachments-lightbox__btn--danger" type="button" aria-label="Mover a la papelera" title="Mover a la papelera" onClick={onTrash}><IonIcon icon={OD_ICONS.delete} /></button> : null}</>} />{!trashMode && shareOpen ? <OrangePhotoShareModal photo={photo} members={members} returnFocusRef={shareButtonRef} onClose={() => setShareOpen(false)} onSave={async body => { await onShareSave(body); setShareOpen(false); notify("Compartición actualizada"); }} /> : null}</>;
}
