/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { createOrangePhotoPublicLink, revokeOrangePhotoPublicLink } from "../../shared/api/orangePhotosApi.js";
import { acquireModalStackLayer, OD_OVERLAY_Z } from "../../shared/overlay/odModalStack.js";

export default function OrangePhotoShareModal({ photo, members, onClose, onSave, onPublicLinkChange, returnFocusRef }) {
  const [visibility,setVisibility]=useState(photo.visibility),[ids,setIds]=useState(photo.shared_user_ids||[]),[busy,setBusy]=useState(false);
  const [publicLink,setPublicLink]=useState(photo.public_link||{enabled:false,token:null,path:null}),[publicBusy,setPublicBusy]=useState(false),[publicError,setPublicError]=useState(""),[copyFeedback,setCopyFeedback]=useState("");
  useEffect(()=>{setVisibility(photo.visibility);setIds(photo.shared_user_ids||[]);setPublicLink(photo.public_link||{enabled:false,token:null,path:null});},[photo]);
  useEffect(()=>{const layer=acquireModalStackLayer(),returnFocus=returnFocusRef?.current,key=event=>{if(event.key==="Escape"){event.stopImmediatePropagation();onClose();}};window.addEventListener("keydown",key,true);return()=>{window.removeEventListener("keydown",key,true);layer.release();returnFocus?.focus();};},[onClose,returnFocusRef]);
  const toggle=id=>setIds(value=>value.includes(id)?value.filter(item=>item!==id):[...value,id]);
  const notifyPublicLink=next=>{onPublicLinkChange?.(next);window.dispatchEvent(new CustomEvent("orangephotos:photo-public-link",{detail:{id:photo.id,publicLink:next}}));};
  const changePublicLink=async regenerate=>{if(regenerate&&!window.confirm("El enlace anterior dejará de funcionar inmediatamente. ¿Quieres continuar?"))return;setPublicBusy(true);setPublicError("");try{const response=await createOrangePhotoPublicLink(photo.id,regenerate),next=response.public_link;setPublicLink(next);notifyPublicLink(next);}catch(error){setPublicError(error.message);}finally{setPublicBusy(false);}};
  const revoke=async()=>{if(!window.confirm("Las personas que tengan el enlace dejarán de poder acceder. ¿Quieres continuar?"))return;setPublicBusy(true);setPublicError("");try{const response=await revokeOrangePhotoPublicLink(photo.id),next=response.public_link;setPublicLink(next);notifyPublicLink(next);}catch(error){setPublicError(error.message);}finally{setPublicBusy(false);}};
  const fullUrl=publicLink.path?`${window.location.origin}${publicLink.path}`:"";
  if(typeof document==="undefined")return null;
  return createPortal(<div className="od-modal-backdrop od-orange-photo-share-backdrop" style={{zIndex:OD_OVERLAY_Z.LIGHTBOX+100}} onMouseDown={event=>{event.stopPropagation();if(event.target===event.currentTarget)onClose();}}><section className="od-modal" role="dialog" aria-modal="true" onMouseDown={event=>event.stopPropagation()}><header className="od-modal-header"><h2 className="od-modal-title">Compartir foto</h2><button className="od-modal-close" type="button" onClick={onClose}>×</button></header><div className="od-modal-body"><label>Visibilidad<select className="od-filter-input" value={visibility} onChange={event=>setVisibility(event.target.value)}><option value="private">Solo yo</option><option value="family">Toda la familia</option><option value="selected">Miembros concretos</option></select></label>{visibility==="selected"?<fieldset className="od-orange-photo-share__members"><legend>Miembros</legend>{members.map(member=><label key={member.id}><input type="checkbox" checked={ids.includes(member.id)} onChange={()=>toggle(member.id)}/>{member.display_name}</label>)}</fieldset>:null}<footer className="od-orange-photos-modal__footer"><button className="od-btn od-btn-secondary" type="button" onClick={onClose}>Cancelar</button><button className="od-btn od-btn-primary" type="button" disabled={busy||visibility==="selected"&&!ids.length} onClick={async()=>{setBusy(true);try{await onSave({visibility,user_ids:ids});}finally{setBusy(false);}}}>Guardar</button></footer>{photo.is_owner?<section className="od-orangephotos-public-link"><h3>Enlace público</h3><p>Cualquier persona con el enlace podrá ver y descargar este elemento.</p>{publicLink.enabled?<><input className="od-filter-input od-orangephotos-public-link__url" readOnly value={fullUrl}/><div className="od-orangephotos-public-link__actions"><button className="od-button-secondary" type="button" disabled={publicBusy} onClick={async()=>{await navigator.clipboard.writeText(fullUrl);setCopyFeedback("Enlace copiado");}}>Copiar enlace</button><button className="od-button-secondary" type="button" disabled={publicBusy} onClick={()=>changePublicLink(true)}>Regenerar enlace</button><button className="od-button-danger" type="button" disabled={publicBusy} onClick={revoke}>Desactivar enlace</button></div></>:<button className="od-modal-primary" type="button" disabled={publicBusy} onClick={()=>changePublicLink(false)}>Crear enlace</button>}{copyFeedback?<p className="od-inline-msg">{copyFeedback}</p>:null}{publicError?<p className="od-status-line od-status-line--error">{publicError}</p>:null}</section>:null}</div></section></div>,document.body);
}
