/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";

export default function OrangePhotoDetailsPanel({ photo, onSave }) {
  const [form, setForm] = useState({});
  useEffect(() => setForm({ title: photo?.title || "", description: photo?.description || "", captured_at: photo?.captured_at?.slice(0, 16) || "", location_name: photo?.location_name || "", latitude: photo?.latitude ?? "", longitude: photo?.longitude ?? "" }), [photo]);
  if (!photo) return null;
  const set = (key, value) => setForm(current => ({ ...current, [key]: value })), displayTitle = photo.title?.trim() || photo.original_filename?.trim() || "Sin título";
  return <aside className="od-orange-photo-details"><h3>Detalles</h3><p><strong>Título visible:</strong> {displayTitle}</p><p><strong>Nombre de archivo:</strong> {photo.original_filename || "—"}</p><label>Título<input className="od-filter-input" value={form.title} onChange={event => set("title", event.target.value)} /></label><label>Descripción<textarea className="od-filter-input" value={form.description} onChange={event => set("description", event.target.value)} /></label><label>Fecha<input className="od-filter-input" type="datetime-local" value={form.captured_at} onChange={event => set("captured_at", event.target.value)} /></label><label>Ubicación<input className="od-filter-input" value={form.location_name} onChange={event => set("location_name", event.target.value)} /></label><div className="od-orange-photo-details__coords"><label>Latitud<input className="od-filter-input" type="number" step="any" value={form.latitude} onChange={event => set("latitude", event.target.value)} /></label><label>Longitud<input className="od-filter-input" type="number" step="any" value={form.longitude} onChange={event => set("longitude", event.target.value)} /></label></div><p>Propietario: {photo.owner_display_name || "—"}</p>{photo.is_owner ? <button className="od-modal-primary" type="button" onClick={() => onSave(form)}>Guardar cambios</button> : null}</aside>;
}
