import { useEffect, useMemo, useRef, useState } from "react";
import OrangeGuestShell from "./OrangeGuestShell.jsx";
import OrangePhotosGrid from "./OrangePhotosGrid.jsx";
import OrangePhotoViewer from "./OrangePhotoViewer.jsx";
import OrangePhotosBulkActions from "./OrangePhotosBulkActions.jsx";
import { getOrangeGuestAlbum, listOrangeGuestAlbumPhotos, getOrangeGuestAlbumPhotoDownload, downloadOrangeGuestAlbumPhotos } from "./orangeGuestAlbumApi.js";

const GUEST_VIEWER_CAPABILITIES = Object.freeze({ select: true, favorite: false, share: false, download: true, editDetails: false, history: false, generatePoster: false, trash: false, restore: false, purge: false });
function groupsFor(items) { const days = new Map(); for (const photo of items) { const date = new Date(photo.captured_at || photo.created_at || Date.now()); const key = date.toISOString().slice(0, 10); if (!days.has(key)) days.set(key, { key, label: date.toLocaleDateString(), photos: [] }); days.get(key).photos.push(photo); } return [{ key: "guest", label: "", days: [...days.values()] }]; }

export default function OrangeGuestAlbumPage({ albumId }) {
  const [state, setState] = useState({ loading: true, error: "", album: null, permissions: null, items: [], page: 1, hasMore: false, loadingMore: false, selectedIndex: null, viewerDownloadUrl: "", viewerLoading: false });
  const [selectedIds, setSelectedIds] = useState(() => new Set()); const [selectionMode, setSelectionMode] = useState(false); const [bulkError, setBulkError] = useState(""); const requestRef = useRef(0);
  useEffect(() => { let active = true; Promise.all([getOrangeGuestAlbum(albumId), listOrangeGuestAlbumPhotos(albumId, { page: 1, per_page: 100 })]).then(([albumResult, photosResult]) => { if (active) setState(current => ({ ...current, loading: false, album: albumResult.album, permissions: albumResult.permissions || null, items: photosResult.items || [], page: photosResult.page || 1, hasMore: photosResult.has_more === true })); }).catch(error => { if (active) setState(current => ({ ...current, loading: false, error: error.message })); }); return () => { active = false; }; }, [albumId]);
  const groups = useMemo(() => groupsFor(state.items), [state.items]); const selectedPhotos = useMemo(() => state.items.filter(photo => selectedIds.has(String(photo.id))), [state.items, selectedIds]);
  const toggleSelected = photo => setSelectedIds(current => { const next = new Set(current); const id = String(photo.id); if (next.has(id)) next.delete(id); else next.add(id); setSelectionMode(next.size > 0); return next; });
  const toggleDaySelection = (_dayKey, photoIds, nextSelected) => setSelectedIds(current => { const next = new Set(current); for (const photoId of photoIds) nextSelected ? next.add(String(photoId)) : next.delete(String(photoId)); setSelectionMode(next.size > 0); return next; });
  const openViewer = async photo => { if (selectionMode) { toggleSelected(photo); return; } const index = state.items.findIndex(item => String(item.id) === String(photo.id)); if (index < 0) return; const request = ++requestRef.current; setState(current => ({ ...current, selectedIndex: index, viewerLoading: true, viewerDownloadUrl: "" })); try { const result = await getOrangeGuestAlbumPhotoDownload(albumId, photo.id); if (request === requestRef.current) setState(current => ({ ...current, viewerLoading: false, viewerDownloadUrl: result.download?.url || "" })); } catch (error) { if (request === requestRef.current) setState(current => ({ ...current, selectedIndex: null, viewerLoading: false, error: error.message })); } };
  const closeViewer = () => setState(current => ({ ...current, selectedIndex: null, viewerDownloadUrl: "" })); const loadMore = async () => { if (state.loadingMore || !state.hasMore) return; setState(current => ({ ...current, loadingMore: true })); try { const result = await listOrangeGuestAlbumPhotos(albumId, { page: state.page + 1, per_page: 100 }); setState(current => ({ ...current, items: [...current.items, ...(result.items || [])], page: result.page || current.page + 1, hasMore: result.has_more === true, loadingMore: false })); } catch (error) { setState(current => ({ ...current, loadingMore: false, error: error.message })); } }; const navigateViewer = delta => { const next = state.items[state.selectedIndex + delta]; if (next) openViewer(next); }; const activePhoto = state.selectedIndex == null ? null : state.items[state.selectedIndex];
  return <OrangeGuestShell><div className="od-orangephotos-page"><section className="od-orangephotos-guest-album"><header className="od-orangephotos-guest-album__header"><button className="od-btn od-btn-secondary" type="button" onClick={() => { window.history.pushState({}, "", "/guest"); window.dispatchEvent(new Event("od-spa-navigate")); }}>Volver a álbumes</button><div><h1 className="od-page-title">{state.album?.title || "Álbum"}</h1>{state.album ? <p>Compartido por {state.album.owner_display_name}</p> : null}</div></header>{state.error ? <p className="od-status-line od-status-line--error">{state.error}</p> : state.loading ? <p className="od-status-line">Cargando álbum…</p> : <>{selectedPhotos.length ? <OrangePhotosBulkActions photos={selectedPhotos} albums={[]} categories={[]} members={[]} capabilities={{ share: false, album: false, download: true, trash: false, favorite: false, edit: false }} onClose={() => { setSelectedIds(new Set()); setSelectionMode(false); setBulkError(""); }} onDownload={() => downloadOrangeGuestAlbumPhotos(albumId, selectedPhotos.map(photo => photo.id))} onAlbum={async () => {}} onCreateAlbum={null} onShare={async () => {}} onTrash={async () => {}} onFavorite={async () => {}} onEdit={async () => {}} /> : null}{bulkError ? <p className="od-status-line od-status-line--error">{bulkError}</p> : null}<OrangePhotosGrid groups={groups} loading={false} selected={selectedIds} selectionMode={selectionMode} onSelect={toggleSelected} onSelectMany={toggleDaySelection} onOpen={openViewer} onActivePeriodChange={() => {}} albumMode publicMode selectable />{state.hasMore ? <button className="od-btn od-btn-secondary" type="button" disabled={state.loadingMore} onClick={loadMore}>{state.loadingMore ? "Cargando…" : "Cargar más"}</button> : null}</>}{activePhoto && state.viewerDownloadUrl && !state.viewerLoading ? <OrangePhotoViewer photo={activePhoto} members={[]} selected={selectedIds.has(String(activePhoto.id))} trashMode={false} onToggleSelected={() => toggleSelected(activePhoto)} onToggleFavorite={() => {}} onClose={closeViewer} onPrevious={() => navigateViewer(-1)} onNext={() => navigateViewer(1)} hasPrevious={state.selectedIndex > 0} hasNext={state.selectedIndex < state.items.length - 1} positionLabel={`${state.selectedIndex + 1} de ${state.items.length}`} capabilities={GUEST_VIEWER_CAPABILITIES} downloadUrl={state.viewerDownloadUrl} /> : null}</section></div></OrangeGuestShell>;
}
