import { useState } from "react";

export default function OrangeAlbumOptionsModal({ album, categories, busy = false, error = "", onClose, onSave }) {
  const [selectedCategoryIds, setSelectedCategoryIds] = useState((album.categories || []).map(category => category.id));
  const [associateDate, setAssociateDate] = useState(Boolean(album.date_mode));
  const [dateMode, setDateMode] = useState(album.date_mode || "single");
  const [dateStart, setDateStart] = useState(album.date_start ? String(album.date_start).slice(0, 10) : "");
  const [dateEnd, setDateEnd] = useState(album.date_end ? String(album.date_end).slice(0, 10) : "");
  const invalid = busy || (associateDate && !dateStart) || (associateDate && dateMode === "range" && (!dateEnd || dateEnd < dateStart));
  const toggle = id => setSelectedCategoryIds(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]);

  return <div className="od-modal-backdrop"><section className="od-modal" role="dialog" aria-modal="true"><header className="od-modal-header"><h2 className="od-modal-title">Opciones del álbum</h2><button type="button" className="od-modal-close" aria-label="Cerrar" onClick={onClose}>×</button></header><form className="od-modal-body od-orange-album-options-modal" onSubmit={event => { event.preventDefault(); onSave({ category_ids: selectedCategoryIds, album_patch: album.is_owner ? associateDate ? { date_mode: dateMode, date_start: dateStart, date_end: dateMode === "single" ? dateStart : dateEnd } : { date_mode: null, date_start: null, date_end: null } : null }); }}><fieldset className="od-orange-album-options-modal__section od-orange-album-options-modal__fieldset"><legend>Categorías</legend>{categories.length ? categories.map(category => <label key={category.id} className="od-orange-album-options-modal__check"><input type="checkbox" checked={selectedCategoryIds.includes(category.id)} onChange={() => toggle(category.id)} /><span>{category.name}</span></label>) : <p>Todavía no has creado categorías.</p>}</fieldset>{album.is_owner ? <fieldset className="od-orange-album-options-modal__section od-orange-album-options-modal__fieldset"><legend>Fecha</legend><label className="od-orange-album-options-modal__check"><input type="checkbox" checked={associateDate} onChange={event => setAssociateDate(event.target.checked)} />Asociar fecha</label>{associateDate ? <><div className="od-orange-album-options-modal__inline-options"><label><input type="radio" checked={dateMode === "single"} onChange={() => setDateMode("single")} />Fecha única</label><label><input type="radio" checked={dateMode === "range"} onChange={() => setDateMode("range")} />Intervalo</label></div><label className="od-form-field"><span className="od-form-label">{dateMode === "single" ? "Fecha" : "Desde"}</span><input className="od-filter-input" type="date" value={dateStart} onChange={event => setDateStart(event.target.value)} /></label>{dateMode === "range" ? <label className="od-form-field"><span className="od-form-label">Hasta</span><input className="od-filter-input" type="date" value={dateEnd} onChange={event => setDateEnd(event.target.value)} /></label> : null}</> : null}</fieldset> : null}{error ? <p className="od-status-line od-status-line--error">{error}</p> : null}<div className="od-modal-actions"><button type="button" className="od-btn od-btn-secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="od-btn od-btn-primary" disabled={invalid}>Guardar</button></div></form></section></div>;
}
