/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import { IonIcon } from "@ionic/react";
import { downloadOutline, expandOutline, informationCircleOutline } from "ionicons/icons";
import { downloadPublicOrangeAlbumZip,getPublicOrangeAlbum,getPublicOrangeAlbumAroundDate,getPublicOrangeAlbumPhotos,getPublicOrangeAlbumTimeline,getPublicOrangePhoto,publicOrangeAlbumPhotoDownloadUrl,publicOrangePhotoDownloadUrl } from "../../shared/api/orangePhotosApi.js";
import OrangePhotosGrid from "./OrangePhotosGrid.jsx";
import OrangePhotosBulkActions from "./OrangePhotosBulkActions.jsx";
import OrangePhotoViewer from "./OrangePhotoViewer.jsx";
import OrangePhotoDetailsPanel from "./OrangePhotoDetailsPanel.jsx";
import OrangePhotosTimeline from "./OrangePhotosTimeline.jsx";
import "./orangePhotos.css";
const PUBLIC_VIEWER_CAPABILITIES=Object.freeze({select:false,favorite:false,share:false,download:true,editDetails:false,history:false,generatePoster:false,trash:false,restore:false,purge:false});
const PUBLIC_BULK_CAPABILITIES=Object.freeze({share:false,album:false,download:true,trash:false,favorite:false,edit:false,addToLibrary:false,hide:false});
function PublicShell({children,albumMode=false,actions=null}){const returnTo=`${window.location.pathname}${window.location.search}`;return <div className="od-orangephotos-public"><header className="od-orangephotos-public__header"><span>OrangeFamily</span>{actions||<a className="od-orangephotos-public__login" href={`/login?returnTo=${encodeURIComponent(returnTo)}`}>Iniciar sesión</a>}</header><main className={`od-orangephotos-public__main${albumMode?" od-orangephotos-public__main--album":""}`}>{children}</main></div>;}
function Status({loading,error}){if(loading)return <p className="od-status-line">Cargandoâ€¦</p>;if(error)return <p className="od-status-line od-status-line--error">Enlace no disponible.</p>;return null;}
function groupsFor(items){const map=new Map();for(const photo of items){const date=photo.captured_at?new Date(photo.captured_at):null,key=date&&!Number.isNaN(date.getTime())?date.toISOString().slice(0,7):"unknown",dayKey=date&&!Number.isNaN(date.getTime())?date.toISOString().slice(0,10):"unknown";if(!map.has(key))map.set(key,{key,label:key==="unknown"?"Sin fecha":new Intl.DateTimeFormat("es-ES",{month:"long",year:"numeric"}).format(date),days:new Map()});const period=map.get(key);if(!period.days.has(dayKey))period.days.set(dayKey,{key:dayKey,label:dayKey==="unknown"?"Fecha desconocida":new Intl.DateTimeFormat("es-ES",{day:"numeric",month:"long"}).format(date),photos:[]});period.days.get(dayKey).photos.push(photo);}return [...map.values()].map(period=>({...period,days:[...period.days.values()]}));}
export function OrangePhotoPublicPage({token}){const[state,setState]=useState({loading:true,error:"",item:null}),[viewerOpen,setViewerOpen]=useState(false),[infoOpen,setInfoOpen]=useState(false);useEffect(()=>{getPublicOrangePhoto(token).then(data=>setState({loading:false,error:"",item:data.item})).catch(()=>setState({loading:false,error:"Enlace no disponible",item:null}));},[token]);const photo=state.item;return <PublicShell><Status loading={state.loading} error={state.error}/>{photo?<article className="od-orangephotos-public-photo"><header className="od-orangephotos-public-photo__header"><h1 className="od-page-title">{photo.title||photo.original_filename||"Foto"}</h1><small>{photo.owner_display_name||""}</small>{photo.description?<p>{photo.description}</p>:null}</header><div className="od-orangephotos-public-photo__media">{photo.media_type==="video"?<video className="od-orangephotos-public-photo__video" src={photo.original_url||photo.preview_url} poster={photo.poster_url||photo.thumbnail_url} controls preload="metadata"/>:<img src={photo.preview_url||photo.original_url||photo.thumbnail_url} alt={photo.title||photo.original_filename||"Foto"} className="od-orangephotos-public-photo__image" onClick={()=>setViewerOpen(true)}/>}</div><div className="od-orangephotos-public-photo__actions"><button className="od-button-secondary" type="button" title="Ampliar" onClick={()=>setViewerOpen(true)}><IonIcon icon={expandOutline}/><span>Ampliar</span></button><button className="od-button-secondary" type="button" title="Ver información" onClick={()=>setInfoOpen(current=>!current)}><IonIcon icon={informationCircleOutline}/><span>Información</span></button><a className="od-button-secondary" title="Descargar" href={publicOrangePhotoDownloadUrl(token)}><IonIcon icon={downloadOutline}/><span>Descargar</span></a></div>{infoOpen?<div className="od-orangephotos-public-photo__info"><OrangePhotoDetailsPanel photo={photo} members={[]} readOnly/></div>:null}</article>:null}{photo&&viewerOpen?<OrangePhotoViewer photo={photo} members={[]} capabilities={PUBLIC_VIEWER_CAPABILITIES} downloadUrl={publicOrangePhotoDownloadUrl(token)} onClose={()=>setViewerOpen(false)} hasPrevious={false} hasNext={false}/>:null}</PublicShell>;}
export function OrangeAlbumPublicPage({ token }) {
  const [album, setAlbum] = useState(null), [items, setItems] = useState([]), [page, setPage] = useState(1), [total, setTotal] = useState(0), [loading, setLoading] = useState(true), [loadingMore, setLoadingMore] = useState(false), [error, setError] = useState(""), [selectedIds, setSelectedIds] = useState(new Set()), [viewer, setViewer] = useState(null);
  const [timeline, setTimeline] = useState([]), [timelineError, setTimelineError] = useState(""), [activePeriod, setActivePeriod] = useState(null), [scrollProgress, setScrollProgress] = useState(0), [timelineScrolling, setTimelineScrolling] = useState(false), [timelineScrubbing, setTimelineScrubbing] = useState(false), [timelineActivated, setTimelineActivated] = useState(false), [windowPagination, setWindowPagination] = useState({ active: false, hasNewer: false, hasOlder: false, newerCursor: null, olderCursor: null });
  const scrollerRef = useRef(null), sentinelRef = useRef(null), loadMoreLockRef = useRef(false), loadNewerLockRef = useRef(false), pendingScrollAnchorRef = useRef(null), pendingTimelineJumpRef = useRef(false), timelineFrameRef = useRef(null), timelineScrollTimerRef = useRef(null), timelineScrubTimerRef = useRef(null), timelineJumpAbortRef = useRef(null), windowGenerationRef = useRef(0);
  const perPage = 30, groups = useMemo(() => groupsFor(items), [items]), viewerIndex = viewer ? items.findIndex(item => item.id === viewer.id) : -1;
  const selectedPhotos = useMemo(() => items.filter(photo => selectedIds.has(photo.id)), [items, selectedIds]);
  const hasMore = windowPagination.active ? windowPagination.hasOlder : items.length < total;
  const mergeItems = (current, incoming) => [...new Map([...current, ...incoming].map(item => [item.id, item])).values()];
  const loadOlder = useCallback(async () => {
    if (!windowPagination.active || !windowPagination.hasOlder || !windowPagination.olderCursor || loadMoreLockRef.current) return;
    loadMoreLockRef.current = true; setLoadingMore(true); const generation = windowGenerationRef.current;
    try { const data = await getPublicOrangeAlbumAroundDate(token, windowPagination.olderCursor, { direction: "older", perPage }); if (generation !== windowGenerationRef.current) return; const incoming = data.items || []; setItems(current => mergeItems(current, incoming)); setWindowPagination(current => ({ ...current, hasOlder: data.has_older === true, olderCursor: data.older_cursor || incoming[incoming.length - 1]?.captured_at || current.olderCursor })); } catch (e) { setError(e.message); } finally { loadMoreLockRef.current = false; setLoadingMore(false); }
  }, [token, windowPagination]);
  const loadNewer = useCallback(async () => {
    if (!windowPagination.active || !windowPagination.hasNewer || !windowPagination.newerCursor || loadNewerLockRef.current) return;
    const scroller = scrollerRef.current, firstVisible = scroller ? [...scroller.querySelectorAll("[data-photo-id]")].find(element => element.getBoundingClientRect().bottom >= scroller.getBoundingClientRect().top) : null;
    loadNewerLockRef.current = true; const generation = windowGenerationRef.current;
    try { const data = await getPublicOrangeAlbumAroundDate(token, windowPagination.newerCursor, { direction: "newer", perPage }); if (generation !== windowGenerationRef.current) return; pendingScrollAnchorRef.current = firstVisible ? { photoId: firstVisible.dataset.photoId, offsetTop: firstVisible.offsetTop } : null; const incoming = data.items || []; setItems(current => mergeItems(incoming, current)); setWindowPagination(current => ({ ...current, hasNewer: data.has_newer === true, newerCursor: data.newer_cursor || incoming[0]?.captured_at || current.newerCursor })); } catch (e) { setError(e.message); } finally { loadNewerLockRef.current = false; }
  }, [token, windowPagination]);
  const scrubToPeriod = useCallback(async period => {
    if (!period) return; const key = `${period.year}-${String(period.month).padStart(2, "0")}`, cursor = period.first_captured_at || period.cursor; if (!cursor) return;
    timelineJumpAbortRef.current?.abort(); const controller = new AbortController(); timelineJumpAbortRef.current = controller; const generation = ++windowGenerationRef.current;
    setTimelineScrubbing(true); setActivePeriod(key); setSelectedIds(new Set()); setViewer(null); pendingTimelineJumpRef.current = true;
    try { const data = await getPublicOrangeAlbumAroundDate(token, cursor, { perPage, signal: controller.signal }); if (controller.signal.aborted || generation !== windowGenerationRef.current) return; const incoming = data.items || []; setItems(incoming); setPage(1); setWindowPagination({ active: true, hasNewer: data.has_newer === true, hasOlder: data.has_older === true, newerCursor: data.newer_cursor || incoming[0]?.captured_at || null, olderCursor: data.older_cursor || incoming[incoming.length - 1]?.captured_at || null }); scrollerRef.current?.scrollTo({ top: 0, behavior: "auto" }); } catch (requestError) { if (requestError?.name === "AbortError" || controller.signal.aborted || generation !== windowGenerationRef.current) return; setError(requestError.message); } finally { if (timelineJumpAbortRef.current === controller) { timelineJumpAbortRef.current = null; clearTimeout(timelineScrubTimerRef.current); timelineScrubTimerRef.current = window.setTimeout(() => setTimelineScrubbing(false), 500); } }
  }, [token]);
  const handleScrollerScroll = useCallback(event => { const element = event.currentTarget; if (element.scrollTop < 300 && windowPagination.active && windowPagination.hasNewer) loadNewer(); if (timelineFrameRef.current) cancelAnimationFrame(timelineFrameRef.current); timelineFrameRef.current = requestAnimationFrame(() => { const maximum = element.scrollHeight - element.clientHeight; setScrollProgress(maximum > 0 ? Math.min(1, Math.max(0, element.scrollTop / maximum)) : 0); if (element.scrollTop > 4) setTimelineActivated(true); }); setTimelineScrolling(true); clearTimeout(timelineScrollTimerRef.current); timelineScrollTimerRef.current = window.setTimeout(() => setTimelineScrolling(false), 900); }, [loadNewer, windowPagination]);
  useEffect(() => { timelineJumpAbortRef.current?.abort(); timelineJumpAbortRef.current = null; windowGenerationRef.current += 1; setAlbum(null); setItems([]); setPage(1); setTotal(0); setSelectedIds(new Set()); setViewer(null); setTimeline([]); setTimelineError(""); setActivePeriod(null); setScrollProgress(0); setTimelineScrolling(false); setTimelineScrubbing(false); setTimelineActivated(false); setWindowPagination({ active: false, hasNewer: false, hasOlder: false, newerCursor: null, olderCursor: null }); setLoading(true); Promise.all([getPublicOrangeAlbum(token), getPublicOrangeAlbumPhotos(token, { page: 1, per_page: perPage })]).then(([albumData, photos]) => { setAlbum(albumData.item); setItems(photos.items || []); setTotal(photos.total || 0); setError(""); }).catch(() => setError("Enlace no disponible")).finally(() => setLoading(false)); getPublicOrangeAlbumTimeline(token).then(data => { setTimeline(data.items || []); setTimelineError(""); }).catch(e => { setTimeline([]); setTimelineError(e.message); }); return () => { timelineJumpAbortRef.current?.abort(); if (timelineFrameRef.current) cancelAnimationFrame(timelineFrameRef.current); clearTimeout(timelineScrollTimerRef.current); clearTimeout(timelineScrubTimerRef.current); }; }, [token]);
  useEffect(() => { if (!pendingTimelineJumpRef.current || !windowPagination.active) return; pendingTimelineJumpRef.current = false; if (windowPagination.hasNewer) loadNewer(); }, [loadNewer, windowPagination]);
  useLayoutEffect(() => { const anchor = pendingScrollAnchorRef.current, scroller = scrollerRef.current; if (!anchor || !scroller) return; const next = scroller.querySelector(`[data-photo-id="${anchor.photoId}"]`); if (next) scroller.scrollTop += next.offsetTop - anchor.offsetTop; pendingScrollAnchorRef.current = null; }, [items]);
  useEffect(() => { const root = scrollerRef.current, sentinel = sentinelRef.current; if (!root || !sentinel) return; const observer = new IntersectionObserver(entries => { if (entries.some(entry => entry.isIntersecting) && !loadingMore && hasMore) { if (windowPagination.active) loadOlder(); else if (!loadMoreLockRef.current) { loadMoreLockRef.current = true; setLoadingMore(true); const next = page + 1; getPublicOrangeAlbumPhotos(token, { page: next, per_page: perPage }).then(data => { setItems(current => mergeItems(current, data.items || [])); setPage(next); setTotal(data.total || 0); }).catch(e => setError(e.message)).finally(() => { loadMoreLockRef.current = false; setLoadingMore(false); }); } } }, { root, rootMargin: "600px 0px", threshold: 0 }); observer.observe(sentinel); return () => observer.disconnect(); }, [token, page, hasMore, loadingMore, windowPagination.active, loadOlder]);
  const toggle = (id, event) => { if (event?.currentTarget?.tagName === "LABEL" && event.target?.tagName !== "INPUT") return; setSelectedIds(current => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; }); };
  const downloadSelection = async () => { const ids = [...selectedIds]; if (!ids.length) return; if (ids.length === 1) { const anchor = document.createElement("a"); anchor.href = publicOrangeAlbumPhotoDownloadUrl(token, ids[0]); anchor.download = ""; anchor.rel = "noopener"; document.body.appendChild(anchor); anchor.click(); anchor.remove(); return; } downloadPublicOrangeAlbumZip(token, ids, downloadError => setError(downloadError.message)); };
  const selectionActions = selectedIds.size > 0 ? <OrangePhotosBulkActions photos={selectedPhotos} albums={[]} members={[]} capabilities={PUBLIC_BULK_CAPABILITIES} onClose={() => setSelectedIds(new Set())} onDownload={downloadSelection}/> : null;
  return <PublicShell albumMode actions={selectionActions}><div className="od-orange-photos__viewport od-orangephotos-public__viewport"><div ref={scrollerRef} onScroll={handleScrollerScroll} className="od-orange-photos__scroller od-orangephotos-public__scroller"><main><Status loading={loading} error={error}/>{album ? <div className="od-orangephotos-public__identity"><h1 className="od-page-title">{album.title}</h1>{album.description ? <p>{album.description}</p> : null}<small>{album.owner_display_name} · {total} elementos</small></div> : null}<OrangePhotosGrid publicMode selectable groups={groups} loading={loading} selected={selectedIds} selectionMode={selectedIds.size > 0} onSelect={toggle} onSelectMany={(_day, ids, select) => setSelectedIds(current => { const next = new Set(current); ids.forEach(id => select ? next.add(id) : next.delete(id)); return next; })} onOpen={setViewer} onActivePeriodChange={setActivePeriod} albumMode/><div ref={sentinelRef} className="od-orange-photos__sentinel"/></main></div><div className={`od-orange-photos__timeline-layer${timelineActivated ? " is-activated" : ""}${timelineScrolling ? " is-scrolling" : ""}${timelineScrubbing ? " is-scrubbing" : ""}`}>{timelineError ? <span className="od-orange-photos__timeline-error" title={timelineError}>!</span> : <OrangePhotosTimeline items={timeline} activePeriod={activePeriod} progress={scrollProgress} visible={timelineScrolling || timelineScrubbing} onScrub={scrubToPeriod}/>}</div></div>{viewer ? <OrangePhotoViewer photo={viewer} members={[]} capabilities={PUBLIC_VIEWER_CAPABILITIES} downloadUrl={publicOrangeAlbumPhotoDownloadUrl(token, viewer.id)} onClose={() => setViewer(null)} hasPrevious={viewerIndex > 0} hasNext={viewerIndex >= 0 && viewerIndex < items.length - 1} onPrevious={() => setViewer(items[viewerIndex - 1])} onNext={() => setViewer(items[viewerIndex + 1])} positionLabel={`${viewerIndex + 1} / ${items.length}`}/> : null}</PublicShell>;
}
