/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import {useCallback,useEffect,useState} from 'react';
import {addPhotoToAlbum,createOrangeAlbum,listOrangeAlbums,listOrangePhotoMembers,listOrangePhotos,restoreOrangePhoto,shareOrangePhoto,trashOrangePhoto,updateOrangePhoto,uploadOrangePhoto} from '../../shared/api/orangePhotosApi.js';
import OrangeAlbumsPanel from './OrangeAlbumsPanel.jsx';import OrangePhotosFiltersBar from './OrangePhotosFiltersBar.jsx';import OrangePhotosGrid from './OrangePhotosGrid.jsx';import OrangePhotoViewer from './OrangePhotoViewer.jsx';import OrangePhotoUploadModal from './OrangePhotoUploadModal.jsx';import OrangePhotoShareModal from './OrangePhotoShareModal.jsx';import './orangePhotos.css';
const initial={search:'',media_type:'',visibility:'',favorite:false,include_trashed:false,album_id:'',page:1,per_page:30};
export default function OrangePhotosPage(){const [filters,setFilters]=useState(initial),[items,setItems]=useState([]),[total,setTotal]=useState(0),[albums,setAlbums]=useState([]),[members,setMembers]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(new Set()),[viewer,setViewer]=useState(null),[uploadOpen,setUploadOpen]=useState(false),[shareOpen,setShareOpen]=useState(false);
const load=useCallback(async()=>{setLoading(true);setError('');try{const data=await listOrangePhotos(filters);setItems(data.items||[]);setTotal(data.total||0);if(viewer)setViewer((data.items||[]).find(x=>x.id===viewer.id)||null);}catch(e){setError(e.message);}finally{setLoading(false);}},[filters,viewer?.id]);
const loadAlbums=useCallback(async()=>{try{setAlbums((await listOrangeAlbums()).items||[]);}catch{/* shown by library */}},[]);
useEffect(()=>{void load();},[load]);useEffect(()=>{void loadAlbums();listOrangePhotoMembers().then(d=>setMembers(d.items||[])).catch(()=>{});},[loadAlbums]);
const toggle=id=>setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n;});
async function save(body){await updateOrangePhoto(viewer.id,body);await load();}
return <div className="od-page"><div className="od-page-inner od-page-inner--full od-orange-photos"><header className="od-orange-photos__header"><div><h1 className="od-page-title">OrangePhotos</h1><p>{total} elementos</p></div><button className="od-modal-primary" type="button" onClick={()=>setUploadOpen(true)}>Subir</button></header><OrangePhotosFiltersBar filters={filters} onChange={setFilters}/>{error?<p className="od-status-line od-status-line--error">{error}</p>:null}<div className="od-orange-photos__layout"><OrangeAlbumsPanel albums={albums} active={filters.album_id} onPick={album_id=>setFilters(f=>({...f,album_id,page:1}))} onCreate={async title=>{await createOrangeAlbum({title});await loadAlbums();}} selectedCount={selected.size} onAddSelected={async()=>{await Promise.all([...selected].map(id=>addPhotoToAlbum(filters.album_id,id)));setSelected(new Set());await load();await loadAlbums();}}/><main><OrangePhotosGrid items={items} loading={loading} selected={selected} onSelect={toggle} onOpen={setViewer}/><div className="od-orange-photos__pagination"><button className="od-button-secondary" disabled={filters.page<=1} onClick={()=>setFilters(f=>({...f,page:f.page-1}))}>Anterior</button><span>Página {filters.page}</span><button className="od-button-secondary" disabled={filters.page*filters.per_page>=total} onClick={()=>setFilters(f=>({...f,page:f.page+1}))}>Siguiente</button></div></main></div></div>{viewer?<OrangePhotoViewer photo={viewer} onClose={()=>setViewer(null)} onSave={save} onShare={()=>setShareOpen(true)} onTrash={async()=>{viewer.is_trashed?await restoreOrangePhoto(viewer.id):await trashOrangePhoto(viewer.id);setViewer(null);await load();}}/>:null}{uploadOpen?<OrangePhotoUploadModal onClose={()=>setUploadOpen(false)} onUpload={async file=>{await uploadOrangePhoto(file);await load();}}/>:null}{shareOpen&&viewer?<OrangePhotoShareModal photo={viewer} members={members} onClose={()=>setShareOpen(false)} onSave={async body=>{await shareOrangePhoto(viewer.id,body);await load();}}/>:null}</div>}
